
language: generic

# Explicitly request container-based infrastructure.
sudo: false

cache:
  directories:
    - "$HOME/.cabal"
    - "$HOME/.emacs.d/.cask"

# Speed up git.
git:
  depth: 5

matrix:
  allow_failures:
     - env: GHC=head EVM_EMACS=emacs-25.3-travis

  include:
    - env: GHC=7.2.2 CABALVER=1.16 INSTALL_HPACK=0 HLINT=0 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC 7.2.2, Cabal 1.16, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.2.2, cabal-install-1.16], sources: [hvr-ghc]}}

    - env: GHC=7.4.2 CABALVER=1.16 INSTALL_HPACK=0 HLINT=0 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC 7.4.2, Cabal 1.16, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.4.2, cabal-install-1.16], sources: [hvr-ghc]}}

    - env: GHC=7.6.3 CABALVER=1.18 INSTALL_HPACK=0 HLINT=0 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC 7.6.3, Cabal 1.18, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.6.3, cabal-install-1.18], sources: [hvr-ghc]}}

    - env: GHC=7.8.4 CABALVER=1.20 INSTALL_HPACK=1 HLINT=0 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC 7.8.4, Cabal 1.20, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.8.4, cabal-install-1.20], sources: [hvr-ghc]}}

    - env: GHC=7.10.3 CABALVER=1.22 INSTALL_HPACK=1 HLINT=0 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC 7.10.3, Cabal 1.22, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.10.3, cabal-install-1.22], sources: [hvr-ghc]}}

    - env: GHC=8.0.2 CABALVER=1.24 INSTALL_HPACK=1 HLINT=0 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC 8.0.2, Cabal 1.24, EMACS 25.3"
      addons: {apt: {packages: [ghc-8.0.2, cabal-install-1.24], sources: [hvr-ghc]}}

    - env: GHC=8.2.2 CABALVER=2.0 INSTALL_HPACK=1 HLINT=0 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC 8.2.2, Cabal 2.0, EMACS 25.3"
      addons: {apt: {packages: [ghc-8.2.2, cabal-install-2.0], sources: [hvr-ghc]}}

    - env: GHC=8.4.1 CABALVER=2.0 INSTALL_HPACK=1 HLINT=0 EVM_EMACS=emacs-24.4-travis
      compiler: "GHC 8.4.1, Cabal 2.2, EMACS 24.4"
      addons: {apt: {packages: [ghc-8.4.1, cabal-install-2.2], sources: [hvr-ghc]}}

    - env: GHC=8.4.1 CABALVER=2.2 ALEXVER=3.1.7 HAPPYVER=1.19.5 INSTALL_HPACK=1 HLINT=1 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC 8.4.1, Cabal 2.2, EMACS 25.3"
      addons: {apt: {packages: [ghc-8.4.1, cabal-install-2.2, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}

    - env: GHC=head CABALVER=head INSTALL_HPACK=1 HLINT=0 EVM_EMACS=emacs-25.3-travis
      compiler: "GHC HEAD, Cabal HEAD, EMACS 25.3"
      addons: {apt: {packages: [ghc-head, cabal-install-head], sources: [hvr-ghc]}}

install: true

before_install:

  # Using compiler above sets CC to an invalid value, so unset it
  - unset CC

  - export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH"

  - |
    if [ -n "$HAPPYVER" ]; then
      export PATH="/opt/happy/$HAPPYVER/bin:$PATH"
    fi
  - |
    if [ -n "$ALEXVER" ]; then
      export PATH="/opt/alex/$ALEXVER/bin:$PATH"
    fi

  - |
    if [ -n "$EVM_EMACS" ]; then
      git clone https://github.com/rejeep/evm.git $HOME/.evm
      export PATH="$HOME/.evm/bin:$PATH"
      evm config path /tmp
      evm install "$EVM_EMACS" --use --skip
      # Use cask to install elisp dependencies
      git clone https://github.com/cask/cask.git "$HOME/.cask"
      export PATH="$HOME/.cask/bin:$PATH"
    fi

install:
  - echo "$PATH"
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - echo "$(ghc-pkg list)"
  - make compile
  - echo "Installing dependencies"
  - |
    if [ "$INSTALL_HPACK" = 1 ]; then
      travis_retry cabal update
      cabal install hsc2hs
      cabal install hpack
    fi
  - |
    if [ "$HLINT" = 1 ]; then
      cabal install hlint
    fi


script:
  - |
    if [ "$HLINT" = 1 ]; then
      make HLINTFLAGS=-c lint
    fi
  - make test
