build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
    TMP: "c:\\tmp"

  matrix:
  - ARGS: "--resolver lts-13" # GHC 8.6.x
  - ARGS: "--resolver lts-12" # GHC 8.4.x
  - ARGS: "--resolver lts-11" # GHC 8.2.2
  - ARGS: "--resolver lts-9" # GHC 8.0.2
  - ARGS: "--resolver lts-7" # GHC 8.0.1
  - ARGS: "--resolver lts-6" # GHC 7.10.3

test_script:

# Install toolchain, but do it silently due to lots of output
- stack %ARGS% setup > nul

# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack %ARGS% --no-terminal test --verbosity=error
#--ghc-options=-Werror
