
;; 1e4   recursion depth is quite safe since:
;; 1.6e4 still works
;; 2e4   makes emacs crash
(setq max-lisp-eval-depth 10000
      ;; to handle all unwind-protects and similar stuff
      ;; in deep recursion
      max-specpdl-size    42000)

;; speeds up startup time considerably, worth to use
(setq gc-cons-threshold (* 50 1024 1024)
      gc-cons-percentage 0.25)



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;Customizations done by emacs customize routine
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector ["#586475" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#839496"])
 '(anything-ff-history-max-length 1024)
 '(anything-ff-newfile-prompt-p nil)
 '(anything-kill-ring-threshold 5)
 '(blink-cursor-mode nil)
 '(blink-matching-delay 0.2)
 '(blink-matching-paren nil)
 '(blink-matching-paren-distance 0)
 '(browse-kill-ring-display-duplicates nil)
 '(browse-kill-ring-highlight-current-entry t)
 '(browse-kill-ring-highlight-inserted-item t)
 '(browse-kill-ring-maximum-display-length 100)
 '(browse-kill-ring-no-duplicates nil)
 '(browse-kill-ring-quit-action (quote save-and-restore))
 '(browse-url-browser-function (quote browse-url-firefox))
 '(browse-url-generic-program nil)
 '(byte-optimize-log nil)
 '(c-comment-only-line-offset 2)
 '(c-default-style (quote ((java-mode . "java") (awk-mode . "awk") (other . "linux"))))
 '(c-hanging-semi&comma-criteria (quote set-from-style))
 '(c-syntactic-indentation t)
 '(case-fold-search nil)
 '(color-theme-directory "/home/sergey/emacs/src/color-theme-6.6.0/themes/")
 '(color-theme-libraries (quote ("/home/sergey/emacs/src/color-theme-6.6.0/themes/color-theme-library.el")))
 '(color-theme-load-all-themes nil)
 '(column-number-mode t)
 '(comint-input-ignoredups t)
 '(comint-scroll-show-maximum-output nil)
 '(compilation-ask-about-save nil)
 '(compilation-auto-jump-to-first-error t)
 '(compilation-read-command nil)
 '(compilation-scroll-output (quote first-error))
 '(compilation-skip-threshold 2)
 '(compile-command "make ")
 '(completion-ignored-extensions (quote (".o" "~" ".bin" ".lbin" ".so" ".a" ".ln" ".blg" ".bbl" ".elc" ".lof" ".glo" ".idx" ".lot" ".svn/" ".hg/" ".git/" ".bzr/" "CVS/" "_darcs/" "_MTN/" ".fmt" ".tfm" ".class" ".fas" ".lib" ".mem" ".x86f" ".sparcf" ".dfsl" ".pfsl" ".d64fsl" ".p64fsl" ".lx64fsl" ".lx32fsl" ".dx64fsl" ".dx32fsl" ".fx64fsl" ".fx32fsl" ".sx64fsl" ".sx32fsl" ".wx64fsl" ".wx32fsl" ".fasl" ".ufsl" ".fsl" ".dxl" ".lo" ".la" ".gmo" ".mo" ".toc" ".aux" ".cp" ".fn" ".ky" ".pg" ".tp" ".vr" ".cps" ".fns" ".kys" ".pgs" ".tps" ".vrs" ".pyc" ".pyo" ".hi")))
 '(completion-show-help nil)
 '(current-language-environment "UTF-8")
 '(debug-on-error nil)
 '(diff-switches "-u --ignore-tab-expansion --ignore-space-change --ignore-blank-lines")
 '(ediff-custom-diff-options "-u --ignore-tab-expansion --ignore-space-change --ignore-blank-lines")
 '(ediff-diff-options "--ignore-tab-expansion --ignore-space-change --ignore-blank-lines")
 '(ediff-merge-split-window-function (quote split-window-vertically))
 '(ediff-patch-options "")
 '(ediff-split-window-function (quote split-window-vertically))
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(eldoc-argument-case (quote downcase))
 '(elp-reset-after-results nil)
 '(emms-cache-file "~/emacs/prog-data/emms/cache")
 '(emms-directory "~/emacs/prog-data/emms")
 '(emms-source-file-exclude-regexp "\\`\\(#.*#\\|.*,v\\|.*~\\|\\.\\.?\\|\\.#.*\\|,.*\\)\\'\\|/\\(CVS\\|RCS\\|\\.arch-ids\\|{arch}\\|,.*\\|\\.git\\|\\.svn\\|_darcs\\)\\(/\\|\\'\\)")
 '(emms-source-playlist-default-format (quote native))
 '(enable-local-variables :all)
 '(enable-recursive-minibuffers t)
 '(eshell-aliases-file "/home/sergey/emacs/prog-data/eshell/alias")
 '(eshell-buffer-maximum-lines 65536)
 '(eshell-buffer-shorthand t)
 '(eshell-cmpl-expand-before-complete t)
 '(eshell-cmpl-ignore-case t)
 '(eshell-command-interpreter-max-length 1024)
 '(eshell-directory-name "~/emacs/prog-data/eshell/")
 '(eshell-error-if-no-glob t)
 '(eshell-glob-include-dot-dot nil)
 '(eshell-hist-ignoredups t)
 '(eshell-history-size 65536)
 '(eshell-password-prompt-regexp "[Pp]ass\\(?:word\\|phrase\\).*:\\s *\\'")
 '(eshell-prefer-lisp-functions t)
 '(eshell-scroll-show-maximum-output nil)
 '(eshell-scroll-to-bottom-on-input nil)
 '(eshell-scroll-to-bottom-on-output nil)
 '(eshell-send-direct-to-subprocesses nil)
 '(eshell-tar-regexp "\\.t\\(?:ar\\(?:\\.\\(?:gz\\|bz2\\|Z\\|7z\\)\\)?\\|gz\\|a[zZ]\\|z2\\|7z\\)\\'")
 '(eval-expression-debug-on-error t)
 '(evil-cross-lines t)
 '(evil-default-cursor (quote (t "#657b83")))
 '(evil-echo-state nil)
 '(evil-ex-search-case (quote sensitive))
 '(evil-flash-delay 60)
 '(evil-move-cursor-back nil)
 '(evil-search-module (quote evil-search))
 '(evil-want-C-i-jump nil)
 '(ex-cycle-other-window nil)
 '(ff-case-fold-search t)
 '(fill-column 80)
 '(find-tag-marker-ring-length 512)
 '(flyspell-issue-message-flag nil)
 '(flyspell-issue-welcome-flag nil)
 '(flyspell-tex-command-regexp "\\(\\(begin\\|end\\)[ 	]*{\\|\\(cite[a-z*]*\\|label\\|ref\\|eqref\\|usepackage\\|documentclass\\|\\(?:sub\\(?:sub\\)?\\)?section\\*?\\|item\\|includegraphics\\|caption\\|clearpage\\|hline\\)[ 	]*\\(\\[[^]]*\\]\\)?{[^{}]*\\)")
 '(flyspell-use-meta-tab nil)
 '(font-lock-maximum-decoration t)
 '(font-lock-maximum-size 33554432)
 '(font-lock-verbose nil)
 '(haskell-literate-default (quote tex))
 '(haskell-program-name "ghci ")
 '(hippie-expand-verbose nil)
 '(history-length 1024)
 '(ibuffer-formats (quote ((mark modified read-only " " (name 32 32 :left :elide) " " (mode 16 16 :left :elide) " " filename-and-process) (mark " " (name 32 -1) " " filename-and-process))))
 '(ibuffer-jump-offer-only-visible-buffers t)
 '(ibuffer-show-empty-filter-groups nil)
 '(icicle-default-value (quote insert-end))
 '(icicle-guess-commands-in-path (quote first-use))
 '(icicle-hide-common-match-in-Completions-flag t)
 '(icicle-highlight-lighter-flag nil)
 '(icicle-incremental-completion-flag (quote always))
 '(icicle-inhibit-ding-flag t)
 '(icicle-isearch-complete-keys (quote ([C-M-tab] "\211" "\357")))
 '(icicle-max-candidates 512)
 '(icicle-modal-cycle-down-keys (quote ([nil mouse-5] [mouse-5])))
 '(icicle-modal-cycle-up-keys (quote ([nil mouse-4] [mouse-4])))
 '(icicle-read+insert-file-name-keys nil)
 '(icicle-sort-orders-alist (quote (("alphabetical case insensitive" . icicle-case-insensitive-string-less-p))))
 '(icicle-top-level-key-bindings (quote (("" icicle-describe-option-of-type t) (abort-recursive-edit icicle-abort-recursive-edit t) (bookmark-jump icicle-bookmark t) (bookmark-jump-other-window icicle-bookmark-other-window t) (bookmark-set icicle-bookmark-cmd t) (minibuffer-keyboard-quit icicle-abort-recursive-edit (fboundp (quote minibuffer-keyboard-quit))) (delete-window icicle-delete-window t) (delete-windows-for icicle-delete-window t) (dired icicle-dired t) (dired-other-window icicle-dired-other-window t) (exchange-point-and-mark icicle-exchange-point-and-mark t) (execute-extended-command icicle-execute-extended-command t) (find-file icicle-file t) (find-file-other-window icicle-file-other-window t) (find-file-read-only icicle-find-file-read-only t) (find-file-read-only-other-window icicle-find-file-read-only-other-window t) (insert-buffer icicle-insert-buffer t) (kill-buffer icicle-kill-buffer t) (kill-buffer-and-its-windows icicle-kill-buffer t) (other-window icicle-other-window-or-frame t) (other-window-or-frame icicle-other-window-or-frame t) (pop-global-mark icicle-goto-global-marker-or-pop-global-mark t) (set-mark-command icicle-goto-marker-or-set-mark-command t) (switch-to-buffer icicle-buffer t) (switch-to-buffer-other-window icicle-buffer-other-window t) (where-is icicle-where-is t) (yank icicle-yank-maybe-completing t) ("jtaa" icicle-find-file-tagged (featurep (quote bookmark+))) ("4jtaa" icicle-find-file-tagged-other-window (featurep (quote bookmark+))) (bmkp-autofile-set icicle-bookmark-a-file (fboundp (quote bmkp-bookmark-a-file))) (bmkp-tag-a-file icicle-tag-a-file (fboundp (quote bmkp-tag-a-file))) (bmkp-untag-a-file icicle-untag-a-file (fboundp (quote bmkp-untag-a-file))) (bmkp-find-file-all-tags icicle-find-file-all-tags (fboundp (quote bmkp-find-file-all-tags))) (bmkp-find-file-all-tags-other-window icicle-find-file-all-tags-other-window (fboundp (quote bmkp-find-file-all-tags))) (bmkp-find-file-all-tags-regexp icicle-find-file-all-tags-regexp (fboundp (quote bmkp-find-file-all-tags-regexp))) (bmkp-find-file-all-tags-regexp-other-window icicle-find-file-all-tags-regexp-other-window (fboundp (quote bmkp-find-file-all-tags-regexp-other-window))) (bmkp-find-file-some-tags icicle-find-file-some-tags (fboundp (quote bmkp-find-file-some-tags))) (bmkp-find-file-some-tags-other-window icicle-find-file-some-tags-other-window (fboundp (quote bmkp-find-file-some-tags-other-window))) (bmkp-find-file-some-tags-regexp icicle-find-file-some-tags-regexp (fboundp (quote bmkp-find-file-some-tags-regexp))) (bmkp-find-file-some-tags-regexp-other-window icicle-find-file-some-tags-regexp-other-window (fboundp (quote bmkp-find-file-some-tags-regexp-other-window))) (bmkp-autofile-jump icicle-bookmark-autofile (fboundp (quote bmkp-autofile-jump))) (bmkp-autofile-jump-other-window icicle-bookmark-autofile-other-window (fboundp (quote bmkp-autofile-jump))) (bmkp-autonamed-jump icicle-bookmark-autonamed (fboundp (quote bmkp-autonamed-jump))) (bmkp-autonamed-jump-other-window icicle-bookmark-autonamed-other-window (fboundp (quote bmkp-autonamed-jump))) (bmkp-autonamed-this-buffer-jump icicle-bookmark-autonamed-this-buffer (fboundp (quote bmkp-autonamed-jump-this-buffer))) (bmkp-autonamed-jump-this-buffer-other-window icicle-bookmark-autonamed-this-buffer-other-window (fboundp (quote bmkp-autonamed-jump))) (bmkp-bookmark-file-jump icicle-bookmark-bookmark-file (fboundp (quote bmkp-bookmark-file-jump))) (bmkp-bookmark-list-jump icicle-bookmark-bookmark-list (fboundp (quote bmkp-bookmark-list-jump))) (bmkp-desktop-jump icicle-bookmark-desktop (fboundp (quote bmkp-desktop-jump))) (bmkp-dired-jump icicle-bookmark-dired (fboundp (quote bmkp-dired-jump))) (bmkp-dired-jump-other-window icicle-bookmark-dired-other-window (fboundp (quote bmkp-dired-jump))) (bmkp-file-jump icicle-bookmark-file (fboundp (quote bmkp-file-jump))) (bmkp-file-jump-other-window icicle-bookmark-file-other-window (fboundp (quote bmkp-file-jump))) (bmkp-file-this-dir-jump icicle-bookmark-file-this-dir (fboundp (quote bmkp-file-this-dir-jump))) (bmkp-file-this-dir-jump-other-window icicle-bookmark-file-this-dir-other-window (fboundp (quote bmkp-file-this-dir-jump))) (bmkp-gnus-jump icicle-bookmark-gnus (fboundp (quote bmkp-gnus-jump))) (bmkp-gnus-jump-other-window icicle-bookmark-gnus-other-window (fboundp (quote bmkp-gnus-jump))) (bmkp-image-jump icicle-bookmark-image (fboundp (quote bmkp-image-jump))) (bmkp-image-jump-other-window icicle-bookmark-image-other-window (fboundp (quote bmkp-image-jump))) (bmkp-info-jump icicle-bookmark-info (fboundp (quote bmkp-info-jump))) (bmkp-info-jump-other-window icicle-bookmark-info-other-window (fboundp (quote bmkp-info-jump))) (bmkp-local-file-jump icicle-bookmark-local-file (fboundp (quote bmkp-local-file-jump))) (bmkp-local-file-jump-other-window icicle-bookmark-local-file-other-window (fboundp (quote bmkp-local-file-jump))) (bmkp-man-jump icicle-bookmark-man (fboundp (quote bmkp-man-jump))) (bmkp-man-jump-other-window icicle-bookmark-man-other-window (fboundp (quote bmkp-man-jump))) (bmkp-non-file-jump icicle-bookmark-non-file (fboundp (quote bmkp-non-file-jump))) (bmkp-non-file-jump-other-window icicle-bookmark-non-file-other-window (fboundp (quote bmkp-non-file-jump))) (bmkp-region-jump icicle-bookmark-region (fboundp (quote bmkp-region-jump))) (bmkp-region-jump-other-window icicle-bookmark-region-other-window (fboundp (quote bmkp-region-jump))) (bmkp-remote-file-jump icicle-bookmark-remote-file (fboundp (quote bmkp-remote-file-jump))) (bmkp-remote-file-jump-other-window icicle-bookmark-remote-file-other-window (fboundp (quote bmkp-remote-file-jump))) (bmkp-specific-buffers-jump icicle-bookmark-specific-buffers (fboundp (quote bmkp-specific-buffers-jump))) (bmkp-specific-buffers-jump-other-window icicle-bookmark-specific-buffers-other-window (fboundp (quote bmkp-specific-buffers-jump))) (bmkp-specific-files-jump icicle-bookmark-specific-files (fboundp (quote bmkp-specific-files-jump))) (bmkp-specific-files-jump-other-window icicle-bookmark-specific-files-other-window (fboundp (quote bmkp-specific-files-jump))) (bmkp-temporary-jump icicle-bookmark-temporary (fboundp (quote bmkp-temporary-jump))) (bmkp-temporary-jump-other-window icicle-bookmark-temporary-other-window (fboundp (quote bmkp-temporary-jump))) (bmkp-this-buffer-jump icicle-bookmark-this-buffer (fboundp (quote bmkp-this-buffer-jump))) (bmkp-this-buffer-jump-other-window icicle-bookmark-this-buffer-other-window (fboundp (quote bmkp-this-buffer-jump))) (bmkp-url-jump icicle-bookmark-url (fboundp (quote bmkp-url-jump))) (bmkp-url-jump-other-window icicle-bookmark-url-other-window (fboundp (quote bmkp-url-jump))) (bmkp-w3m-jump icicle-bookmark-w3m (fboundp (quote bmkp-w3m-jump))) (bmkp-w3m-jump-other-window icicle-bookmark-w3m-other-window (fboundp (quote bmkp-w3m-jump))) (bmkp-all-tags-jump icicle-bookmark-all-tags (fboundp (quote bmkp-all-tags-jump))) (bmkp-all-tags-jump-other-window icicle-bookmark-all-tags-other-window (fboundp (quote bmkp-all-tags-jump))) (bmkp-all-tags-regexp-jump icicle-bookmark-all-tags-regexp (fboundp (quote bmkp-all-tags-regexp-jump))) (bmkp-all-tags-regexp-jump-other-window icicle-bookmark-all-tags-regexp-other-window (fboundp (quote bmkp-all-tags-regexp-jump))) (bmkp-some-tags-jump icicle-bookmark-some-tags (fboundp (quote bmkp-some-tags-jump))) (bmkp-some-tags-jump-other-window icicle-bookmark-some-tags-other-window (fboundp (quote bmkp-some-tags-jump))) (bmkp-some-tags-regexp-jump icicle-bookmark-some-tags-regexp (fboundp (quote bmkp-some-tags-regexp-jump))) (bmkp-some-tags-regexp-jump-other-window icicle-bookmark-some-tags-regexp-other-window (fboundp (quote bmkp-some-tags-regexp-jump))) (bmkp-file-all-tags-jump icicle-bookmark-file-all-tags (fboundp (quote bmkp-file-all-tags-jump))) (bmkp-file-all-tags-jump-other-window icicle-bookmark-file-all-tags-other-window (fboundp (quote bmkp-file-all-tags-jump))) (bmkp-file-all-tags-regexp-jump icicle-bookmark-file-all-tags-regexp (fboundp (quote bmkp-file-all-tags-regexp-jump))) (bmkp-file-all-tags-regexp-jump-other-window icicle-bookmark-file-all-tags-regexp-other-window (fboundp (quote bmkp-file-all-tags-regexp-jump))) (bmkp-file-some-tags-jump icicle-bookmark-file-some-tags (fboundp (quote bmkp-file-some-tags-jump))) (bmkp-file-some-tags-jump-other-window icicle-bookmark-file-some-tags-other-window (fboundp (quote bmkp-file-some-tags-jump))) (bmkp-file-some-tags-regexp-jump icicle-bookmark-file-some-tags-regexp (fboundp (quote bmkp-file-some-tags-regexp-jump))) (bmkp-file-some-tags-regexp-jump-other-window icicle-bookmark-file-some-tags-regexp-other-window (fboundp (quote bmkp-file-some-tags-regexp-jump))) (bmkp-file-this-dir-all-tags-jump icicle-bookmark-file-this-dir-all-tags (fboundp (quote bmkp-file-this-dir-all-tags-jump))) (bmkp-file-this-dir-all-tags-jump-other-window icicle-bookmark-file-this-dir-all-tags-other-window (fboundp (quote bmkp-file-this-dir-all-tags-jump))) (bmkp-file-this-dir-all-tags-regexp-jump icicle-bookmark-file-this-dir-all-tags-regexp (fboundp (quote bmkp-file-this-dir-all-tags-regexp-jump))) (bmkp-file-this-dir-all-tags-regexp-jump-other-window icicle-bookmark-file-this-dir-all-tags-regexp-other-window (fboundp (quote bmkp-file-this-dir-all-tags-regexp-jump))) (bmkp-file-this-dir-some-tags-jump icicle-bookmark-file-this-dir-some-tags (fboundp (quote bmkp-file-this-dir-some-tags-jump))) (bmkp-file-this-dir-some-tags-jump-other-window icicle-bookmark-file-this-dir-some-tags-other-window (fboundp (quote bmkp-file-this-dir-some-tags-jump))) (bmkp-file-this-dir-some-tags-regexp-jump icicle-bookmark-file-this-dir-some-tags-regexp (fboundp (quote bmkp-file-this-dir-some-tags-regexp-jump))) (bmkp-file-this-dir-some-tags-regexp-jump-other-window icicle-bookmark-file-this-dir-some-tags-regexp-other-window (fboundp (quote bmkp-file-this-dir-some-tags-regexp-jump))) (find-tag icicle-find-tag (fboundp (quote command-remapping))) (find-tag-other-window icicle-find-first-tag-other-window t) (pop-tag-mark icicle-pop-tag-mark (fboundp (quote command-remapping))) (eval-expression icicle-pp-eval-expression (fboundp (quote command-remapping))) (pp-eval-expression icicle-pp-eval-expression (fboundp (quote command-remapping))))))
 '(icicle-top-level-when-sole-completion-delay 0.01)
 '(icicle-top-level-when-sole-completion-flag nil)
 '(icicle-word-completion-keys nil)
 '(ielm-noisy nil)
 '(ielm-prompt "> ")
 '(imaxima-fnt-size "huge")
 '(imaxima-label-color "#dc322f" t)
 '(imaxima-latex-preamble "")
 '(imaxima-maxima-options "-q --disable-readline --preload-lisp='/home/sergey/emacs/src/maxima/imaxima.lisp'")
 '(imaxima-pt-size 12)
 '(imaxima-scale-factor 1.0)
 '(imaxima-tmp-dir "~/emacs/prog-data/imaxima-tmp/")
 '(inferior-lisp-program "sbcl")
 '(inferior-octave-buffer "*Octave*")
 '(inferior-octave-startup-args (quote ("--no-line-editing")))
 '(inferior-octave-startup-file "/home/sergey/.octaverc")
 '(jit-lock-chunk-size 1000)
 '(jit-lock-stealth-time nil)
 '(lisp-indent-function (quote common-lisp-indent-function))
 '(lisp-indent-maximum-backtracking 20)
 '(lisp-indent-offset nil)
 '(lisp-interaction-mode-hook nil)
 '(lisp-lambda-list-keyword-alignment nil)
 '(lisp-lambda-list-keyword-parameter-indentation 0)
 '(lisp-loop-keyword-indentation 4)
 '(lisp-simple-loop-indentation 3)
 '(lisp-tag-body-indentation 2)
 '(maxima-args (quote ("-q" "--disable-readline" "--preload-lisp=/home/sergey/emacs/src/maxima/maxima-tex.lisp")))
 '(maxima-input-history-file "~/emacs/prog-data/.maxima_history")
 '(maxima-input-history-length 65536)
 '(maxima-save-input-history t)
 '(maxima-use-full-color-in-process-buffer t)
 '(nxml-slash-auto-complete-flag t)
 '(octave-block-offset 4)
 '(octave-continuation-offset 8)
 '(open-paren-in-column-0-is-defun-start nil)
 '(org-highlight-latex-fragments-and-specials t)
 '(org-pretty-entities t)
 '(package-archive-upload-base "/home/sergey/emacs/prog-data/packages")
 '(package-archives (quote (("gnu" . "http://elpa.gnu.org/packages/") ("ELPA" . "http://tromey.com/elpa/") ("marmalade" . "http://marmalade-repo.org/packages/"))))
 '(package-user-dir "~/emacs/prog-data/elpa")
 '(pcomplete-expand-before-complete t)
 '(pcomplete-ignore-case t)
 '(preview-auto-cache-preamble t)
 '(preview-transparent-color (quote (default :background)))
 '(prolog-underscore-wordchar-flag t)
 '(py-load-pymacs-p nil)
 '(py-start-run-py-shell nil)
 '(py-temp-directory "/home/sergey/emacs/prog-data/python-tmp")
 '(quack-dir "~/emacs/prog-data/quack")
 '(quack-fontify-style (quote emacs))
 '(quack-global-menu-p nil)
 '(quack-remember-new-programs-p nil)
 '(quack-programs (quote ()))
 '(quack-quiet-warnings-p t)
 '(quack-remap-find-file-bindings-p nil)
 '(quack-tabs-are-evil-p t)
 '(reb-re-syntax (quote read))
 '(regexp-search-ring-max 1024)
 '(rng-schema-locating-files (quote ("schemas.xml" "/home/sergey/emacs/nxhtml/xhtml-transitional-in-nxml/schemas.xml" "/usr/local/share/emacs/24.0.95/etc/schema/schemas.xml")))
 '(save-completions-file-name "~/emacs/prog-data/completions")
 '(scheme-mit-dialect nil)
 '(search-ring-max 1024)
 '(slime-auto-connect (quote ask))
 '(slime-complete-symbol-function (quote slime-fuzzy-complete-symbol))
 '(slime-ed-use-dedicated-frame nil)
 '(slime-enable-evaluate-in-emacs t)
 '(slime-header-line-p nil)
 '(slime-kill-without-query-p t)
 '(slime-load-failed-fasl (quote never))
 '(slime-repl-history-file "/home/sergey/emacs/prog-data/slime-repl-history")
 '(slime-repl-history-remove-duplicates t)
 '(slime-repl-history-trim-whitespaces t)
 '(slime-repl-track-package-in-prompt t)
 '(slime-repl-wrap-history t)
 '(smex-history-length 100)
 '(speedbar-use-images nil)
 '(sql-input-ring-separator "
--
")
 '(sql-pop-to-buffer-after-send-region t)
 '(sr-history-length 100)
 '(sr-listing-switches "--time-style=locale --group-directories-first -alDhgG")
 '(sr-refresh-hook (quote (auto-insert)))
 '(sr-show-hidden-files t)
 '(sr-start-hook (quote (auto-insert)))
 '(sr-use-commander-keys nil)
 '(sr-window-split-style (quote horizontal))
 '(sr-windows-locked nil)
 '(tabbar-buffer-groups-function (quote tabbar-buffer-groups+))
 '(tabbar-cycling-scope (quote tabs))
 '(tabbar-home-function nil)
 '(tabbar-home-help-function nil)
 '(tabbar-inhibit-functions (quote (tabbar-default-inhibit-function tabbar-dont-show)))
 '(tabbar-scroll-left-function nil)
 '(tabbar-scroll-left-help-function nil)
 '(tabbar-scroll-right-function nil)
 '(tabbar-scroll-right-help-function nil)
 '(tags-case-fold-search nil)
 '(tags-loop-revert-buffers t)
 '(tags-revert-without-query t)
 '(temporary-file-directory "/home/sergey/emacs/prog-data/tmp")
 '(tramp-auto-save-directory "/home/sergey/emacs/prog-data/tramp")
 '(undo-limit 1000000)
 '(undo-outer-limit 32000000)
 '(undo-strong-limit 1000000)
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify))
 '(uniquify-strip-common-suffix nil)
 '(user-full-name "Sergey Vinokurov")
 '(user-mail-address "serg.foo@gmail.com")
 '(vim-mode t)
 '(vim:max-jumplist 100)
 '(vim:shift-width 4)
 '(warning-suppress-types (quote ((\(undo\ discard-info\)))))
 '(which-func-format (quote which-func-current))
 '(which-func-maxout 1000000))

(add-to-list 'load-path "/home/sergey/emacs")

(load-library "dotemacs")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;Custom function declarations
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;Customizations done by emacs customize routine
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; Emacs/W3 Configuration
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;; '(compilation-error ((t (:inherit font-lock-warning-face :weight bold))))
;; '(compilation-info ((t (:foreground "#b58900"))))
;; '(completions-common-part ((t (:inherit match))))
;; '(diff-added ((t (:foreground "#859900"))))
;; '(diff-changed ((t (:foreground "#b58900"))))
;; '(diff-file-header ((t (:foreground "#6c71c4"))))
;; '(diff-header ((t (:foreground "#268bd2"))))
;; '(diff-indicator-removed ((t (:inherit diff-removed))))
;; '(diff-removed ((t (:foreground "#dc322f"))))
;; '(ediff-current-diff-A ((t (:background "#e0ffd0"))))
;; '(ediff-current-diff-Ancestor ((t (:background "#ffcff9"))))
;; '(ediff-current-diff-B ((t (:background "#ffffbf"))))
;; '(ediff-current-diff-C ((t (:background "#ffd9b9"))))
;; '(ediff-fine-diff-A ((t (:background "#cfefff"))))
;; '(ediff-fine-diff-Ancestor ((t (:background "#dfffdf"))))
;; '(ediff-fine-diff-B ((t (:background "#cfffff"))))
;; '(ediff-fine-diff-C ((t (:background "#ccfbff"))))
;; '(eshell-ls-archive ((((class color) (background light)) (:foreground "#6c71c4"))))
;; '(eshell-ls-directory ((((class color) (background light)) (:foreground "#268bd2"))))
;; '(eshell-ls-executable ((t (:foreground "#859900"))))
;; '(eshell-ls-missing ((t (:foreground "#dc322f"))))
;; '(eshell-ls-special ((((class color) (background light)) (:foreground "#d33682"))))
;; '(eshell-ls-symlink ((t (:foreground "#2aa198"))))
;; '(eshell-prompt ((t (:foreground "#d33682"))))
;; '(flyspell-duplicate ((t (:background "#ffffbb"))))
;; '(flyspell-incorrect ((t (:background "#ffdff2"))))
;; '(font-latex-bold-face ((t (:inherit bold))))
;; '(font-latex-doctex-documentation-face ((t (:inherit font-lock-doc-face))))
;; '(font-latex-doctex-preprocessor-face ((t (:inherit font-lock-preprocessor-face))))
;; '(font-latex-italic-face ((t (:inherit italic))))
;; '(font-latex-math-face ((t (:foreground "#2aa198"))))
;; '(font-latex-sectioning-0-face ((t (:inherit font-latex-sectioning-1-face :height 1.05))))
;; '(font-latex-sectioning-1-face ((t (:inherit font-latex-sectioning-2-face :height 1.05))))
;; '(font-latex-sectioning-2-face ((t (:inherit font-latex-sectioning-3-face :height 1.05))))
;; '(font-latex-sectioning-3-face ((t (:inherit font-latex-sectioning-4-face :height 1.05))))
;; '(font-latex-sectioning-4-face ((t (:inherit font-latex-sectioning-5-face :height 1.05))))
;; '(font-latex-sectioning-5-face ((t (:foreground "#d33682"))))
;; '(font-latex-sedate-face ((t (:foreground "#b58900"))))
;; '(font-latex-slide-title-face ((t (:foreground "#d33682"))))
;; '(font-latex-string-face ((t (:inherit font-lock-string-face))))
;; '(font-latex-verbatim-face ((t (:foreground "#6c71c4"))))
;; '(font-latex-warning-face ((t (:foreground "#6c71c4"))))
;; '(font-lock-builtin-face ((t (:foreground "#b58900"))))
;; '(font-lock-constant-face ((t (:foreground "#cb4b16"))))
;; '(font-lock-doc-face ((t (:foreground "#6c71c4"))))
;; '(font-lock-function-name-face ((t (:foreground "#268bd2"))))
;; '(font-lock-keyword-face ((t (:foreground "#b58900"))))
;; '(font-lock-negation-char-face ((t (:foreground "#2aa198"))))
;; '(font-lock-preprocessor-face ((t (:foreground "#cb4b16"))))
;; '(font-lock-string-face ((t (:foreground "#2aa198"))))
;; '(font-lock-type-face ((t (:foreground "#859900"))))
;; '(font-lock-variable-name-face ((t (:inherit font-lock-function-name-face))))
;; '(font-lock-warning-face ((t (:inherit warning))))
;; '(header-line ((t (:background "#eee8d5" :foreground "#657b83"))))
;; '(hexl-address-region ((t (:inherit header-line))))
;; '(hexl-ascii-region ((t (:background "#fdf6e3"))))
;; '(highlight ((t (:background "#eee8d5"))))
;; '(icicle-Completions-instruction-1 ((t (:foreground "#268bd2"))))
;; '(icicle-Completions-instruction-2 ((t (:foreground "#d33682"))))
;; '(icicle-common-match-highlight-Completions ((t (:underline t))))
;; '(icicle-complete-input ((t (:foreground "#859900"))))
;; '(icicle-completion ((t (:foreground "#dc322f"))))
;; '(icicle-current-candidate-highlight ((t (:inherit lazy-highlight))))
;; '(icicle-extra-candidate ((t (:underline "black"))))
;; '(icicle-historical-candidate ((t (:underline "#859900"))))
;; '(icicle-match-highlight-Completions ((t (:background "#eee8d5"))))
;; '(icicle-mode-line-help ((t (:foreground "#268bd2"))))
;; '(icicle-multi-command-completion ((t (:weight bold))))
;; '(icicle-mustmatch-completion ((t (:weight bold))))
;; '(icicle-saved-candidate ((t (:slant italic))))
;; '(icicle-search-context-level-1 ((t (:underline "#dc322f"))))
;; '(icicle-search-context-level-2 ((t (:underline "#cb4b16"))))
;; '(icicle-search-context-level-3 ((t (:underline "#b58900"))))
;; '(icicle-search-context-level-4 ((t (:underline "#859900"))))
;; '(icicle-search-context-level-5 ((t (:underline "#2aa198"))))
;; '(icicle-search-context-level-6 ((t (:underline "#268bd2"))))
;; '(icicle-search-context-level-7 ((t (:underline "#6c71c4"))))
;; '(icicle-search-context-level-8 ((t (:underline "#586e75"))))
;; '(icicle-search-current-input ((t (:underline "#d33682"))))
;; '(icicle-search-main-regexp-others ((t (:background "#eee8d5"))))
;; '(icicle-whitespace-highlight ((t (:background "#d33682"))))
;; '(ido-indicator ((t (:foreground "#268bd2" :width condensed))))
;; '(ido-only-match ((t (:foreground "#2aa198"))))
;; '(ido-subdir ((t (:foreground "#cb4b16"))))
;; '(isearch ((t (:inherit lazy-highlight))))
;; '(italic ((t (:underline t))))
;; '(lazy-highlight ((t (:background "#cfefff"))))
;; '(link ((t (:foreground "#6c71c4" :underline t))))
;; '(match ((t (:background "#e0ffd0"))))
;; '(minibuffer-prompt ((t (:foreground "#6c71c4"))))
;; '(paren-face-no-match ((t (:underline "#b58900"))))
;; '(quack-pltish-class-defn-face ((((class color) (background light)) (:foreground "#6c71c4"))))
;; '(quack-pltish-defn-face ((((class color) (background light)) (:foreground "#268bd2"))))
;; '(quack-pltish-keyword-face ((t (:foreground "#586e75"))))
;; '(quack-pltish-module-defn-face ((((class color) (background light)) (:foreground "#6c71c4"))))
;; '(quack-threesemi-semi-face ((((class color) (background light)) (:foreground "#93a1a1"))))
;; '(quack-threesemi-text-face ((((class color) (background light)) (:foreground "#93a1a1"))))
;; '(query-replace ((t (:background "#ffdfff"))))
;; '(rainbow-delimiters-depth-1-face ((t (:foreground "#839496"))))
;; '(rainbow-delimiters-depth-2-face ((t (:foreground "#dc322f"))))
;; '(rainbow-delimiters-depth-3-face ((t (:foreground "#cb4b16"))))
;; '(rainbow-delimiters-depth-4-face ((t (:foreground "#b58900"))))
;; '(rainbow-delimiters-depth-5-face ((t (:foreground "#859900"))))
;; '(rainbow-delimiters-depth-6-face ((t (:foreground "#2aa198"))))
;; '(rainbow-delimiters-depth-7-face ((t (:foreground "#268bd2"))))
;; '(rainbow-delimiters-depth-8-face ((t (:foreground "#6c71c4"))))
;; '(rainbow-delimiters-depth-9-face ((t (:foreground "#d33682"))))
;; '(rainbow-delimiters-unmatched-face ((t (:background "#d33682"))))
;; '(region ((t (:background "#eee8d5" :underline t))))
;; '(sh-heredoc ((((class color) (background light)) (:foreground "#2aa198"))))
;; '(sh-quoted-exec ((t (:foreground "#d33682"))))
;; '(show-paren-match ((t (:background "#fdf6e3" :foreground "#657b83" :underline "#d33682"))))
;; '(show-paren-match-face ((t (:underline "#dc322f"))))
;; '(sldb-detailed-frame-line-face ((t nil)))
;; '(sldb-frame-label-face ((t (:foreground "#073642"))))
;; '(sldb-restartable-frame-line-face ((t (:foreground "#2aa198"))))
;; '(sldb-section-face ((t (:foreground "#073642"))))
;; '(slime-error-face ((t (:underline "#dc322f"))))
;; '(slime-note-face ((t (:underline "#859900"))))
;; '(slime-style-warning-face ((t (:underline "#b58900"))))
;; '(slime-warning-face ((t (:underline "#cb4b16"))))
;; '(tabbar-button-face ((t (:inherit tabbar-default-face :box (:line-width 2 :color "white" :style released-button) :foreground "dark red"))))
;; '(tabbar-default-face ((t (:inherit variable-pitch :height 0.8 :foreground "#657b83" :background "#eee8d5"))))
;; '(tabbar-selected-face ((t (:inherit tabbar-default-face :foreground "#d33682"))))
;; '(tabbar-separator-face ((t (:inherit tabbar-default-face))))
;; '(tabbar-unselected-face ((t (:inherit tabbar-default-face))))
;; '(table-cell ((t nil)))
;; '(tex-math ((t (:foreground "#2aa198"))))
;; '(trailing-whitespace ((t (:background "#d33682"))))
;; '(undo-tree-visualizer-active-branch-face ((t (:weight bold))))
;; '(undo-tree-visualizer-current-face ((t (:foreground "#dc322f"))))
;; '(undo-tree-visualizer-register-face ((t (:foreground "#b58900"))))
;; '(vim:search ((t (:underline "#268bd2"))))
;; '(vim:substitute ((t (:underline "#d33682"))))
;; '(warning ((t (:foreground "#dc322f"))))
;; '(whitespace-line ((t (:underline "#dc322f"))))
;; '(yas/field-highlight-face ((t (:underline "#2aa198"))))

;; '(anything-M-x-key-face ((t (:foreground "#cb4b16" :underline t))))
;; '(anything-apt-installed ((t (:foreground "#859900"))))
;; '(anything-bmkext-file ((t (:foreground "#268bd2"))))
;; '(anything-bmkext-gnus ((t (:foreground "#d33682"))))
;; '(anything-bmkext-info ((t (:foreground "#859900"))))
;; '(anything-bmkext-man ((t (:foreground "#cb4b16"))))
;; '(anything-bmkext-no--file ((t (:foreground "#93a1a1"))))
;; '(anything-bmkext-w3m ((t (:foreground "#b58900"))))
;; '(anything-bookmarks-su-face ((t (:foreground "#dc322f"))))
;; '(anything-candidate-number ((t (:foreground "#cb4b16"))))
;; '(anything-emms-playlist ((t (:foreground "#2aa198" :underline t))))
;; '(anything-ff-directory ((t (:foreground "#268bd2"))))
;; '(anything-ff-executable ((t (:foreground "#859900"))))
;; '(anything-ff-file ((t (:inherit default))))
;; '(anything-ff-invalid-symlink ((t (:foreground "#d33682" :underline t))))
;; '(anything-ff-prefix ((t (:foreground "#b58900"))))
;; '(anything-ff-symlink ((t (:foreground "#cb4b16"))))
;; '(anything-grep-file ((t (:foreground "#6c71c4"))))
;; '(anything-grep-finish ((t (:inherit success))))
;; '(anything-grep-lineno ((t (:foreground "#859900"))))
;; '(anything-grep-running ((t (:foreground "#cb4b16"))))
;; '(anything-lisp-completion-info ((t (:foreground "#dc3226"))))
;; '(anything-lisp-show-completion ((t (:inherit default :weight bold))))
;; '(anything-overlay-line-face ((t (:foreground "#dc322f" :weight bold))))
;; '(anything-visible-mark ((t (:foreground "#2aa198" :weight bold))))
;; '(anything-w3m-bookmarks-face ((t (:foreground "#268bd2" :underline t))))


;; '(font-lock-constant-face ((t (:foreground "#cb4b16"))))
;; '(font-lock-doc-face ((t (:foreground "#6c71c4"))))
;; '(font-lock-keyword-face ((t (:foreground "#859900"))))
;; '(font-lock-negation-char-face ((t (:foreground "#2aa198"))))
;; '(font-lock-string-face ((t (:foreground "#cb4b16"))))
;; '(font-lock-warning-face ((t (:foreground "#dc322f"))))




