name: CI

on:
  push:
    paths:
      - '**.el'
      - '**ci.yml'
      - 'Makefile'
    branches:
      - master

  pull_request:
    paths:
      - '**.el'
      - '**ci.yml'
      - 'Makefile'
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emacs_version: [25.1, 25.3, 26.3, 27.2, 28.2, snapshot]

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Checkout Company
        uses: actions/checkout@v3

      - name: Run tests
        run: make test-batch

      - name: Run compilation
        run: make compile-warn
