blank_issues_enabled: false
contact_links:
  - name: "💡 Suggest a feature"
    url: https://github.com/magit/ghub/discussions
    about: Start a discussion suggest an improvement or a new feature.
  - name: "🆘 Ask the community for support"
    url: https://www.reddit.com/r/emacs
    about: Please also consider supporting others.
  - name: "🆘 Ask the maintainers for support"
    url: https://github.com/magit/ghub/discussions
    about: Please keep in mind that our bandwidth is limited.
  - name: "ℹ️ Ghub FAQ"
    url: https://github.com/magit/ghub/wiki/FAQ
    about: Others might have had the same question before.
  - name: "ℹ️ Ghub Manual"
    url: https://magit.vc/manual/ghub/#Top
    about: The fine manual may also be of use.
