name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot
        include:
          - emacs_version: 26.3
            target: deploy-manual
          - emacs_version: 26.3
            target: check-external
    steps:
    - uses: cachix/install-nix-action@v6
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Install stack and ghc
      run: nix-env -iA stack ghc -f '<nixpkgs>'
    - name: Install texinfo
      if: matrix.target == 'deploy-manual'
      run: nix-env -iA texinfo -f '<nixpkgs>'
    - name: Run make
      run: make ${{ matrix.target || 'check' }}
      continue-on-error: ${{ matrix.emacs_version == 'snapshot' && (! matrix.target) }}
