;; shell-completion-ghc.el --- -*- lexical-binding: t; -*-

;; Copyright (C) Sergey Vinokurov
;;
;; Author: Sergey Vinokurov <serg.foo@gmail.com>
;; Created: 18 July 2026
;; Description:

(eval-when-compile
  (require 'macro-util)
  (require 'shell-completion))

(eval-and-compile
  (defconst pcomplete-ghc-flags
    (let* ((known-options '(("--show-iface" (pcmpl-haskell-hi-files))
                            (("--exclude-module" "-dep-makefile" "-o") (pcmpl-entries))
                            (("-i" "-I" "-L" "--dumpdir" "-hidir" "-odir" "-outputdir" "-stubdir" "-tmpdir" "-working-dir") (pcmpl-dirs))
                            (("-package-db" "-package-env") (pcmpl-entries-ignoring-common))
                            ("-dth-dec-file" (pcmpl-entries))
                            "-v"
                            "-v1"
                            "-v2"
                            "-v3"
                            "-O"
                            "-O0"
                            "-O1"
                            "-O2"
                            "-fdiagnostics-color=always"
                            "-fdiagnostics-color=auto"
                            "-fdiagnostics-color=never"
                            "-rtsopts"
                            "-rtsopts=none"
                            "-rtsopts=some"
                            "-rtsopts=all"))
           (known-options-names
            (--mapcat (if (stringp it)
                          (list (seq-take-while (lambda (c) (not (eq c ?=))) it))
                        (let ((fst (car it)))
                          (if (stringp fst)
                              (list fst)
                            fst)))
                      known-options))
           (known-options-names-ht (alist->hash-table (--map (cons it t) known-options-names))))
      (append known-options
              (--filter (not (gethash it known-options-names-ht))
                        (quote
                         ;; (insert
                         ;;  (pp-to-string
                         ;;   (process-lines "ghc" "--show-options")))
                         ("-package-db" "-clear-package-db" "-no-global-package-db"
                          "-no-user-package-db" "-global-package-db" "-user-package-db"
                          "-package-conf" "-no-user-package-conf" "-package-name"
                          "-this-unit-id" "-working-dir" "-this-package-name" "-hidden-module"
                          "-reexported-module" "-package" "-plugin-package-id"
                          "-plugin-package" "-package-id" "-hide-package" "-hide-all-packages"
                          "-hide-all-plugin-packages" "-package-env" "-ignore-package"
                          "-syslib" "-distrust-all-packages" "-trust" "-distrust"
                          "-base-unit-id" "-n" "-cpp" "-F" "-#include" "-v" "-j" "-jsem"
                          "-instantiated-with" "-this-component-id" "-H" "-Rghc-timing" "-prof"
                          "-eventlog" "-debug" "-threaded" "-single-threaded" "-ticky"
                          "-static" "-dynamic" "-rdynamic" "-relative-dynlib-paths"
                          "-copy-libs-when-linking" "-pie" "-no-pie" "-pgmlo" "-pgmlc"
                          "-pgmlas" "-pgmlm" "-pgmi" "-pgmL" "-pgmP" "-pgmJSP" "-pgmCmmP"
                          "-pgmF" "-pgmc" "-pgmcxx" "-pgmc-supports-no-pie" "-pgms" "-pgma"
                          "-pgml" "-pgml-supports-no-pie" "-pgmwindres" "-pgmar" "-pgmotool"
                          "-pgminstall_name_tool" "-pgmranlib" "-optlm" "-optlo" "-optlc"
                          "-optlas" "-opti" "-optL" "-optP" "-optJSP" "-optCmmP" "-optF"
                          "-optc" "-optcxx" "-opta" "-optl" "-optwindres" "-split-sections"
                          "-dep-suffix" "-dep-makefile" "-include-cpp-deps" "-include-pkg-deps"
                          "-exclude-module" "-no-link" "-shared" "-staticlib" "--merge-objs"
                          "-dynload" "-dylib-install-name" "-L" "-l" "-framework-path"
                          "-framework" "-odir" "-o" "-dyno" "-ohi" "-dynohi" "-osuf" "-dynosuf"
                          "-hcsuf" "-hisuf" "-hiesuf" "-dynhisuf" "-hidir" "-hiedir" "-tmpdir"
                          "-stubdir" "-dumpdir" "-outputdir" "-ddump-file-prefix"
                          "-dynamic-too" "-keep-hc-file" "-keep-hc-files" "-keep-hscpp-file"
                          "-keep-hscpp-files" "-keep-s-file" "-keep-s-files" "-keep-llvm-file"
                          "-keep-llvm-files" "-keep-tmp-files" "-keep-hi-file"
                          "-no-keep-hi-file" "-keep-hi-files" "-no-keep-hi-files"
                          "-keep-o-file" "-no-keep-o-file" "-keep-o-files" "-no-keep-o-files"
                          "-no-auto-link-packages" "-no-hs-main" "-fno-state-hack"
                          "-fno-opt-coercion" "-with-rtsopts" "-rtsopts" "-rtsopts=all"
                          "-rtsopts=some" "-rtsopts=none" "-rtsopts=ignore"
                          "-rtsopts=ignoreAll" "-no-rtsopts" "-no-rtsopts-suggestions"
                          "-dhex-word-literals" "-ghcversion-file" "-main-is" "-haddock"
                          "-no-haddock" "-haddock-opts" "-hpcdir" "-ticky-allocd" "-ticky-LNE"
                          "-ticky-ap-thunk" "-ticky-dyn-thunk" "-ticky-tag-checks" "-recomp"
                          "-no-recomp" "-fmax-errors" "-fno-max-errors" "-freverse-errors"
                          "-fno-reverse-errors" "-D" "-U" "-I" "-i" "-dppr-user-length"
                          "-dppr-cols" "-fdiagnostics-color=auto" "-fdiagnostics-color=always"
                          "-fdiagnostics-color=never" "-fprint-error-index-links=auto"
                          "-fprint-error-index-links=always" "-fprint-error-index-links=never"
                          "-dsuppress-all" "-dstg-stats" "-ddump-cmm" "-ddump-cmm-from-stg"
                          "-ddump-cmm-raw" "-ddump-cmm-verbose" "-ddump-cmm-verbose-by-proc"
                          "-ddump-cmm-cfg" "-ddump-cmm-cbe" "-ddump-cmm-switch"
                          "-ddump-cmm-proc" "-ddump-cmm-sp" "-ddump-cmm-sink" "-ddump-cmm-caf"
                          "-ddump-cmm-procmap" "-ddump-cmm-split" "-ddump-cmm-info"
                          "-ddump-cmm-cps" "-ddump-cmm-opt" "-ddump-cmm-thread-sanitizer"
                          "-ddump-cfg-weights" "-ddump-core-stats" "-ddump-asm" "-ddump-js"
                          "-ddump-asm-native" "-ddump-asm-liveness" "-ddump-asm-regalloc"
                          "-ddump-asm-conflicts" "-ddump-asm-regalloc-stages"
                          "-ddump-asm-stats" "-ddump-llvm" "-ddump-c-backend" "-ddump-deriv"
                          "-ddump-ds" "-ddump-ds-preopt" "-ddump-foreign" "-ddump-inlinings"
                          "-ddump-verbose-inlinings" "-ddump-rule-firings"
                          "-ddump-rule-rewrites" "-ddump-simpl-trace" "-ddump-occur-anal"
                          "-ddump-parsed" "-ddump-parsed-ast" "-dkeep-comments" "-ddump-rn"
                          "-ddump-rn-ast" "-ddump-simpl" "-ddump-simpl-iterations"
                          "-ddump-spec" "-ddump-spec-constr" "-ddump-prep" "-ddump-late-cc"
                          "-ddump-stg-from-core" "-ddump-stg-unarised" "-ddump-stg-final"
                          "-ddump-stg-cg" "-ddump-stg" "-ddump-stg-tags"
                          "-ddump-stg-from-js-sinker" "-ddump-call-arity" "-ddump-exitify"
                          "-ddump-stranal" "-ddump-str-signatures" "-ddump-dmdanal"
                          "-ddump-dmd-signatures" "-ddump-cpranal" "-ddump-cpr-signatures"
                          "-ddump-tc" "-ddump-tc-ast" "-ddump-hie" "-ddump-types"
                          "-ddump-rules" "-ddump-cse" "-ddump-float-out" "-ddump-full-laziness"
                          "-ddump-float-in" "-ddump-liberate-case"
                          "-ddump-static-argument-transformation" "-ddump-worker-wrapper"
                          "-ddump-rn-trace" "-ddump-if-trace" "-ddump-cs-trace"
                          "-ddump-tc-trace" "-ddump-ec-trace" "-ddump-splices" "-dth-dec-file"
                          "-ddump-rn-stats" "-ddump-opt-cmm" "-ddump-simpl-stats" "-ddump-bcos"
                          "-dsource-stats" "-dverbose-core2core" "-dverbose-stg2stg"
                          "-ddump-hi" "-ddump-minimal-imports" "-ddump-hpc" "-ddump-ticked"
                          "-ddump-mod-cycles" "-ddump-mod-map" "-ddump-timings"
                          "-ddump-view-pattern-commoning" "-ddump-to-file" "-ddump-hi-diffs"
                          "-ddump-rtti" "-dlint" "-dcore-lint" "-dlinear-core-lint"
                          "-dstg-lint" "-dcmm-lint" "-dasm-lint" "-dannot-lint"
                          "-dtag-inference-checks" "-dshow-passes" "-dipe-stats"
                          "-dfaststring-stats" "-dno-llvm-mangler" "-dno-typeable-binds"
                          "-ddump-debug" "-ddump-json" "-dppr-debug" "-ddebug-output"
                          "-dno-debug-output" "-ddump-faststrings" "-msse" "-msse2" "-msse3"
                          "-mssse3" "-msse4" "-msse4.2" "-mbmi" "-mbmi2" "-mavx" "-mavx2"
                          "-mavx512cd" "-mavx512er" "-mavx512f" "-mavx512pf" "-mfma"
                          "-fplugin-opt" "-fplugin-trustworthy" "-fplugin" "-fclear-plugins"
                          "-ffrontend-opt" "-fplugin-library" "-Onot" "-O"
                          "-fbinary-blob-threshold" "-fmax-relevant-binds"
                          "-fno-max-relevant-binds" "-fmax-valid-hole-fits"
                          "-fno-max-valid-hole-fits" "-fmax-refinement-hole-fits"
                          "-fno-max-refinement-hole-fits" "-frefinement-level-hole-fits"
                          "-fno-refinement-level-hole-fits" "-fwrite-if-compression"
                          "-fllvm-pass-vectors-in-regs" "-fmax-uncovered-patterns"
                          "-fmax-pmcheck-models" "-fsimplifier-phases"
                          "-fmax-simplifier-iterations" "-fmax-pmcheck-iterations"
                          "-fsimpl-tick-factor" "-fdmd-unbox-width" "-fspec-constr-threshold"
                          "-fno-spec-constr-threshold" "-fspec-constr-count"
                          "-fno-spec-constr-count" "-fspec-constr-recursive"
                          "-fliberate-case-threshold" "-fno-liberate-case-threshold"
                          "-drule-check" "-dinline-check" "-freduction-depth"
                          "-fconstraint-solver-iterations" "-fgivens-expansion-fuel"
                          "-fwanteds-expansion-fuel" "-fqcs-expansion-fuel" "-fcontext-stack"
                          "-ftype-function-depth" "-fstrictness-before" "-ffloat-lam-args"
                          "-ffloat-all-lams" "-fstg-lift-lams-rec-args"
                          "-fstg-lift-lams-rec-args-any" "-fstg-lift-lams-non-rec-args"
                          "-fstg-lift-lams-non-rec-args-any" "-fstg-lift-lams-known"
                          "-fno-stg-lift-lams-known" "-fproc-alignment"
                          "-fblock-layout-weights" "-fhistory-size"
                          "-funfolding-creation-threshold" "-funfolding-use-threshold"
                          "-funfolding-fun-discount" "-funfolding-dict-discount"
                          "-funfolding-case-threshold" "-funfolding-case-scaling"
                          "-funfolding-keeness-factor" "-fmax-worker-args"
                          "-fmax-forced-spec-args" "-fmax-inline-alloc-size"
                          "-fmax-inline-memcpy-insns" "-fmax-inline-memset-insns"
                          "-dinitial-unique" "-dunique-increment" "-auto-all" "-no-auto-all"
                          "-auto" "-no-auto" "-caf-all" "-no-caf-all" "-fprof-auto"
                          "-fprof-auto-top" "-fprof-auto-exported" "-fprof-auto-calls"
                          "-fno-prof-auto" "-fprof-callers" "-fasm" "-fvia-c" "-fvia-C"
                          "-fllvm" "-fno-code" "-fbyte-code" "-fobject-code" "-fglasgow-exts"
                          "-fno-glasgow-exts" "-fpackage-trust" "-fno-safe-infer"
                          "-fno-safe-haskell" "-fPIC" "-fno-PIC" "-fPIE" "-fno-PIE" "-g"
                          "-dppr-case-as-let" "-dppr-ticks" "-dsuppress-ticks"
                          "-dsuppress-stg-free-vars" "-dsuppress-stg-exts"
                          "-dsuppress-stg-reps" "-dsuppress-coercions"
                          "-dsuppress-coercion-types" "-dsuppress-idinfo"
                          "-dsuppress-unfoldings" "-dsuppress-module-prefixes"
                          "-dsuppress-timestamps" "-dsuppress-type-applications"
                          "-dsuppress-type-signatures" "-dsuppress-uniques"
                          "-dsuppress-var-kinds" "-dsuppress-core-sizes" "-dno-ppr-case-as-let"
                          "-dno-ppr-ticks" "-dno-suppress-ticks" "-dno-suppress-stg-free-vars"
                          "-dno-suppress-stg-exts" "-dno-suppress-stg-reps"
                          "-dno-suppress-coercions" "-dno-suppress-coercion-types"
                          "-dno-suppress-idinfo" "-dno-suppress-unfoldings"
                          "-dno-suppress-module-prefixes" "-dno-suppress-timestamps"
                          "-dno-suppress-type-applications" "-dno-suppress-type-signatures"
                          "-dno-suppress-uniques" "-dno-suppress-var-kinds"
                          "-dno-suppress-core-sizes" "-fasm-shortcutting"
                          "-fbuilding-cabal-package" "-fcall-arity" "-fexitification"
                          "-fcase-merge" "-fcase-folding" "-fcmm-elim-common-blocks"
                          "-fcmm-sink" "-fcmm-static-pred" "-fcse" "-fstg-cse"
                          "-fstg-lift-lams" "-fcpr-anal" "-fdefer-diagnostics"
                          "-fdefer-type-errors" "-fdefer-typed-holes"
                          "-fdefer-out-of-scope-variables" "-fdiagnostics-show-caret"
                          "-fdiagnostics-as-json" "-fdump-with-ways" "-fdicts-cheap"
                          "-fdicts-strict" "-fdmd-tx-dict-sel" "-fdo-eta-reduction"
                          "-fdo-lambda-eta-expansion" "-fdo-clever-arg-eta-expansion"
                          "-feager-blackholing" "-forig-thunk-info" "-fembed-manifest"
                          "-fenable-rewrite-rules" "-fenable-th-splice-warnings"
                          "-ferror-spans" "-fexcess-precision" "-fexpose-all-unfoldings"
                          "-fexpose-overloaded-unfoldings" "-fkeep-auto-rules"
                          "-fexpose-internal-symbols" "-fexternal-dynamic-refs"
                          "-fexternal-interpreter" "-ffamily-application-cache" "-ffloat-in"
                          "-fforce-recomp" "-fignore-optim-changes" "-fignore-hpc-changes"
                          "-ffull-laziness" "-ffun-to-thunk" "-flocal-float-out"
                          "-flocal-float-out-top-level" "-fgen-manifest" "-fghci-history"
                          "-fghci-leak-check" "-finter-module-far-jumps" "-fvalidate-ide-info"
                          "-fghci-sandbox" "-fhelpful-errors" "-fhpc" "-fignore-asserts"
                          "-fignore-interface-pragmas" "-firrefutable-tuples" "-fkeep-going"
                          "-flate-dmd-anal" "-flate-specialise" "-fliberate-case"
                          "-floopification" "-fblock-layout-cfg" "-fblock-layout-weightless"
                          "-fomit-interface-pragmas" "-fomit-yields" "-foptimal-applicative-do"
                          "-fpedantic-bottoms" "-fpre-inlining" "-fprint-explicit-foralls"
                          "-fprint-explicit-kinds" "-fprint-explicit-coercions"
                          "-fprint-explicit-runtime-reps" "-fprint-equality-relations"
                          "-fprint-axiom-incomps" "-fprint-unicode-syntax"
                          "-fprint-expanded-synonyms" "-fprint-potential-instances"
                          "-fprint-redundant-promotion-ticks" "-fprint-typechecker-elaboration"
                          "-fprof-cafs" "-fprof-count-entries" "-fprof-late"
                          "-fprof-late-overloaded" "-fprof-late-overloaded-calls"
                          "-fprof-manual" "-fprof-late-inline" "-fregs-graph"
                          "-fregs-iterative" "-frewrite-rules" "-fshared-implib"
                          "-fspec-constr" "-fspec-constr-keen" "-fspecialise" "-fspecialize"
                          "-fspecialise-aggressively" "-fspecialize-aggressively"
                          "-fcross-module-specialise" "-fcross-module-specialize"
                          "-fpolymorphic-specialisation" "-fspecialise-incoherents"
                          "-finline-generics" "-finline-generics-aggressively"
                          "-fstatic-argument-transformation" "-fstrictness" "-fuse-rpaths"
                          "-fwrite-interface" "-fwrite-if-simplified-core"
                          "-fwrite-if-self-recomp" "-fwrite-if-self-recomp-flags"
                          "-fwrite-ide-info" "-funbox-small-strict-fields"
                          "-funbox-strict-fields" "-funoptimized-core-for-interpreter"
                          "-fversion-macros" "-fworker-wrapper" "-fworker-wrapper-cbv"
                          "-fsolve-constant-dicts" "-fcatch-nonexhaustive-cases"
                          "-falignment-sanitisation" "-fcheck-prim-bounds" "-fadd-bco-name"
                          "-fnum-constant-folding" "-fcore-constant-folding" "-ffast-pap-calls"
                          "-fspec-eval" "-fspec-eval-dictfun" "-fcmm-control-flow"
                          "-fshow-warning-groups" "-fhide-source-paths" "-fshow-loaded-modules"
                          "-fwhole-archive-hs-libs" "-fkeep-cafs" "-flink-rts"
                          "-fbyte-code-and-object-code" "-fprefer-byte-code"
                          "-fobject-determinism" "-fcompact-unwind" "-fshow-error-context"
                          "-fcmm-thread-sanitizer" "-fsplit-sections" "-fbreak-points"
                          "-fdistinct-constructor-tables" "-finfo-table-map"
                          "-finfo-table-map-with-stack" "-finfo-table-map-with-fallback"
                          "-fshow-hole-constraints" "-fshow-valid-substitutions"
                          "-fshow-valid-hole-fits" "-fsort-valid-hole-fits"
                          "-fsort-by-size-hole-fits" "-fsort-by-subsumption-hole-fits"
                          "-fabstract-refinement-hole-fits" "-fshow-hole-matches-of-hole-fits"
                          "-fshow-provenance-of-hole-fits" "-fshow-type-of-hole-fits"
                          "-fshow-type-app-of-hole-fits" "-fshow-type-app-vars-of-hole-fits"
                          "-fshow-docs-of-hole-fits" "-funclutter-valid-hole-fits"
                          "-fno-asm-shortcutting" "-fno-building-cabal-package"
                          "-fno-call-arity" "-fno-exitification" "-fno-case-merge"
                          "-fno-case-folding" "-fno-cmm-elim-common-blocks" "-fno-cmm-sink"
                          "-fno-cmm-static-pred" "-fno-cse" "-fno-stg-cse" "-fno-stg-lift-lams"
                          "-fno-cpr-anal" "-fno-defer-diagnostics" "-fno-defer-type-errors"
                          "-fno-defer-typed-holes" "-fno-defer-out-of-scope-variables"
                          "-fno-diagnostics-show-caret" "-fno-diagnostics-as-json"
                          "-fno-dump-with-ways" "-fno-dicts-cheap" "-fno-dicts-strict"
                          "-fno-dmd-tx-dict-sel" "-fno-do-eta-reduction"
                          "-fno-do-lambda-eta-expansion" "-fno-do-clever-arg-eta-expansion"
                          "-fno-eager-blackholing" "-fno-orig-thunk-info" "-fno-embed-manifest"
                          "-fno-enable-rewrite-rules" "-fno-enable-th-splice-warnings"
                          "-fno-error-spans" "-fno-excess-precision"
                          "-fno-expose-all-unfoldings" "-fno-expose-overloaded-unfoldings"
                          "-fno-keep-auto-rules" "-fno-expose-internal-symbols"
                          "-fno-external-dynamic-refs" "-fno-external-interpreter"
                          "-fno-family-application-cache" "-fno-float-in" "-fno-force-recomp"
                          "-fno-ignore-optim-changes" "-fno-ignore-hpc-changes"
                          "-fno-full-laziness" "-fno-fun-to-thunk" "-fno-local-float-out"
                          "-fno-local-float-out-top-level" "-fno-gen-manifest"
                          "-fno-ghci-history" "-fno-ghci-leak-check"
                          "-fno-inter-module-far-jumps" "-fno-validate-ide-info"
                          "-fno-ghci-sandbox" "-fno-helpful-errors" "-fno-hpc"
                          "-fno-ignore-asserts" "-fno-ignore-interface-pragmas"
                          "-fno-irrefutable-tuples" "-fno-keep-going" "-fno-late-dmd-anal"
                          "-fno-late-specialise" "-fno-liberate-case" "-fno-loopification"
                          "-fno-block-layout-cfg" "-fno-block-layout-weightless"
                          "-fno-omit-interface-pragmas" "-fno-omit-yields"
                          "-fno-optimal-applicative-do" "-fno-pedantic-bottoms"
                          "-fno-pre-inlining" "-fno-print-explicit-foralls"
                          "-fno-print-explicit-kinds" "-fno-print-explicit-coercions"
                          "-fno-print-explicit-runtime-reps" "-fno-print-equality-relations"
                          "-fno-print-axiom-incomps" "-fno-print-unicode-syntax"
                          "-fno-print-expanded-synonyms" "-fno-print-potential-instances"
                          "-fno-print-redundant-promotion-ticks"
                          "-fno-print-typechecker-elaboration" "-fno-prof-cafs"
                          "-fno-prof-count-entries" "-fno-prof-late"
                          "-fno-prof-late-overloaded" "-fno-prof-late-overloaded-calls"
                          "-fno-prof-manual" "-fno-prof-late-inline" "-fno-regs-graph"
                          "-fno-regs-iterative" "-fno-rewrite-rules" "-fno-shared-implib"
                          "-fno-spec-constr" "-fno-spec-constr-keen" "-fno-specialise"
                          "-fno-specialize" "-fno-specialise-aggressively"
                          "-fno-specialize-aggressively" "-fno-cross-module-specialise"
                          "-fno-cross-module-specialize" "-fno-polymorphic-specialisation"
                          "-fno-specialise-incoherents" "-fno-inline-generics"
                          "-fno-inline-generics-aggressively"
                          "-fno-static-argument-transformation" "-fno-strictness"
                          "-fno-use-rpaths" "-fno-write-interface"
                          "-fno-write-if-simplified-core" "-fno-write-if-self-recomp"
                          "-fno-write-if-self-recomp-flags" "-fno-write-ide-info"
                          "-fno-unbox-small-strict-fields" "-fno-unbox-strict-fields"
                          "-fno-unoptimized-core-for-interpreter" "-fno-version-macros"
                          "-fno-worker-wrapper" "-fno-worker-wrapper-cbv"
                          "-fno-solve-constant-dicts" "-fno-catch-nonexhaustive-cases"
                          "-fno-alignment-sanitisation" "-fno-check-prim-bounds"
                          "-fno-add-bco-name" "-fno-num-constant-folding"
                          "-fno-core-constant-folding" "-fno-fast-pap-calls" "-fno-spec-eval"
                          "-fno-spec-eval-dictfun" "-fno-cmm-control-flow"
                          "-fno-show-warning-groups" "-fno-hide-source-paths"
                          "-fno-show-loaded-modules" "-fno-whole-archive-hs-libs"
                          "-fno-keep-cafs" "-fno-link-rts" "-fno-byte-code-and-object-code"
                          "-fno-prefer-byte-code" "-fno-object-determinism"
                          "-fno-compact-unwind" "-fno-show-error-context"
                          "-fno-cmm-thread-sanitizer" "-fno-split-sections" "-fno-break-points"
                          "-fno-distinct-constructor-tables" "-fno-info-table-map"
                          "-fno-info-table-map-with-stack" "-fno-info-table-map-with-fallback"
                          "-fno-show-hole-constraints" "-fno-show-valid-substitutions"
                          "-fno-show-valid-hole-fits" "-fno-sort-valid-hole-fits"
                          "-fno-sort-by-size-hole-fits" "-fno-sort-by-subsumption-hole-fits"
                          "-fno-abstract-refinement-hole-fits"
                          "-fno-show-hole-matches-of-hole-fits"
                          "-fno-show-provenance-of-hole-fits" "-fno-show-type-of-hole-fits"
                          "-fno-show-type-app-of-hole-fits"
                          "-fno-show-type-app-vars-of-hole-fits" "-fno-show-docs-of-hole-fits"
                          "-fno-unclutter-valid-hole-fits" "-W" "-Werror" "-Wwarn" "-Wnot" "-w"
                          "-Wcompat" "-Wunused-binds" "-Wextended-warnings" "-Wdefault"
                          "-Wextra" "-Wall" "-Weverything" "-Wno-compat" "-Wno-unused-binds"
                          "-Wno-extended-warnings" "-Wno-default" "-Wno-extra" "-Wno-all"
                          "-Wno-everything" "-Werror=compat" "-Werror=unused-binds"
                          "-Werror=extended-warnings" "-Werror=default" "-Werror=extra"
                          "-Werror=all" "-Werror=everything" "-Wwarn=compat"
                          "-Wwarn=unused-binds" "-Wwarn=extended-warnings" "-Wwarn=default"
                          "-Wwarn=extra" "-Wwarn=all" "-Wwarn=everything" "-Wno-error=compat"
                          "-Wno-error=unused-binds" "-Wno-error=extended-warnings"
                          "-Wno-error=default" "-Wno-error=extra" "-Wno-error=all"
                          "-Wno-error=everything" "-Wduplicate-exports"
                          "-Wduplicate-constraints" "-Wredundant-constraints" "-Whi-shadowing"
                          "-Wimplicit-prelude" "-Wincomplete-patterns"
                          "-Wincomplete-uni-patterns" "-Wincomplete-record-updates"
                          "-Woverflowed-literals" "-Wempty-enumerations" "-Wmissing-fields"
                          "-Wmissing-import-lists" "-Wmissing-methods" "-Wmissing-signatures"
                          "-Wmissing-local-sigs" "-Wmissing-local-signatures"
                          "-Wname-shadowing" "-Woverlapping-patterns" "-Wtype-defaults"
                          "-Wmonomorphism-restriction" "-Wunused-top-binds"
                          "-Wunused-local-binds" "-Wunused-pattern-binds" "-Wunused-imports"
                          "-Wunused-matches" "-Wunused-type-patterns" "-Wunused-foralls"
                          "-Wunused-record-wildcards" "-Wredundant-bang-patterns"
                          "-Wredundant-record-wildcards" "-Wdeprecated-flags"
                          "-Wmissing-monadfail-instances" "-Wsemigroup" "-Wdodgy-exports"
                          "-Wdodgy-imports" "-Worphans" "-Wauto-orphans" "-Widentities"
                          "-Wtabs" "-Wunrecognised-pragmas" "-Wmisplaced-pragmas"
                          "-Wdodgy-foreign-imports" "-Wunused-do-bind" "-Wwrong-do-bind"
                          "-Walternative-layout-rule-transitional" "-Wunsafe" "-Wsafe"
                          "-Wtrustworthy-safe" "-Wmissed-specialisations"
                          "-Wmissed-specializations" "-Wall-missed-specialisations"
                          "-Wall-missed-specializations" "-Wunsupported-calling-conventions"
                          "-Wunsupported-llvm-version" "-Wmissed-extra-shared-lib"
                          "-Winline-rule-shadowing" "-Wtyped-holes" "-Wpartial-type-signatures"
                          "-Wmissing-exported-sigs" "-Wmissing-exported-signatures"
                          "-Wunticked-promoted-constructors" "-Wderiving-typeable"
                          "-Wdeferred-type-errors" "-Wdeferred-out-of-scope-variables"
                          "-Wnoncanonical-monad-instances" "-Wnoncanonical-monadfail-instances"
                          "-Wnoncanonical-monoid-instances"
                          "-Wmissing-pattern-synonym-signatures" "-Wunrecognised-warning-flags"
                          "-Wsimplifiable-class-constraints" "-Wcpp-undef"
                          "-Wunbanged-strict-patterns" "-Wmissing-home-modules"
                          "-Wpartial-fields" "-Wmissing-export-lists" "-Winaccessible-code"
                          "-Wstar-is-type" "-Wstar-binder" "-Wimplicit-kind-vars"
                          "-Wmissing-space-after-bang" "-Wmissing-deriving-strategies"
                          "-Wprepositive-qualified-module" "-Wunused-packages"
                          "-Winferred-safe-imports" "-Wmissing-safe-haskell-mode"
                          "-Wcompat-unqualified-imports" "-Wderiving-defaults"
                          "-Winvalid-haddock" "-Woperator-whitespace-ext-conflict"
                          "-Woperator-whitespace" "-Wambiguous-fields" "-Wimplicit-lift"
                          "-Wmissing-kind-signatures" "-Wmissing-poly-kind-signatures"
                          "-Wmissing-exported-pattern-synonym-signatures"
                          "-Wredundant-strictness-flags" "-Wforall-identifier"
                          "-Wunicode-bidirectional-format-characters" "-Wgadt-mono-local-binds"
                          "-Wtype-equality-out-of-scope" "-Wtype-equality-requires-operators"
                          "-Wloopy-superclass-solve" "-Wterm-variable-capture"
                          "-Wmissing-role-annotations" "-Wimplicit-rhs-quantification"
                          "-Wincomplete-export-warnings" "-Wincomplete-record-selectors"
                          "-Wbadly-levelled-types" "-Wbadly-staged-types"
                          "-Winconsistent-flags" "-Wdata-kinds-tc"
                          "-Wdefaulted-exception-context" "-Wview-pattern-signatures"
                          "-Wuseless-specialisations" "-Wuseless-specializations"
                          "-Wdeprecated-pragmas" "-Wrule-lhs-equalities"
                          "-Wunusable-unpack-pragmas" "-Wpattern-namespace-specifier"
                          "-Wno-duplicate-exports" "-Wno-duplicate-constraints"
                          "-Wno-redundant-constraints" "-Wno-hi-shadowing"
                          "-Wno-implicit-prelude" "-Wno-incomplete-patterns"
                          "-Wno-incomplete-uni-patterns" "-Wno-incomplete-record-updates"
                          "-Wno-overflowed-literals" "-Wno-empty-enumerations"
                          "-Wno-missing-fields" "-Wno-missing-import-lists"
                          "-Wno-missing-methods" "-Wno-missing-signatures"
                          "-Wno-missing-local-sigs" "-Wno-missing-local-signatures"
                          "-Wno-name-shadowing" "-Wno-overlapping-patterns"
                          "-Wno-type-defaults" "-Wno-monomorphism-restriction"
                          "-Wno-unused-top-binds" "-Wno-unused-local-binds"
                          "-Wno-unused-pattern-binds" "-Wno-unused-imports"
                          "-Wno-unused-matches" "-Wno-unused-type-patterns"
                          "-Wno-unused-foralls" "-Wno-unused-record-wildcards"
                          "-Wno-redundant-bang-patterns" "-Wno-redundant-record-wildcards"
                          "-Wno-deprecated-flags" "-Wno-missing-monadfail-instances"
                          "-Wno-semigroup" "-Wno-dodgy-exports" "-Wno-dodgy-imports"
                          "-Wno-orphans" "-Wno-auto-orphans" "-Wno-identities" "-Wno-tabs"
                          "-Wno-unrecognised-pragmas" "-Wno-misplaced-pragmas"
                          "-Wno-dodgy-foreign-imports" "-Wno-unused-do-bind"
                          "-Wno-wrong-do-bind" "-Wno-alternative-layout-rule-transitional"
                          "-Wno-unsafe" "-Wno-safe" "-Wno-trustworthy-safe"
                          "-Wno-missed-specialisations" "-Wno-missed-specializations"
                          "-Wno-all-missed-specialisations" "-Wno-all-missed-specializations"
                          "-Wno-unsupported-calling-conventions"
                          "-Wno-unsupported-llvm-version" "-Wno-missed-extra-shared-lib"
                          "-Wno-inline-rule-shadowing" "-Wno-typed-holes"
                          "-Wno-partial-type-signatures" "-Wno-missing-exported-sigs"
                          "-Wno-missing-exported-signatures"
                          "-Wno-unticked-promoted-constructors" "-Wno-deriving-typeable"
                          "-Wno-deferred-type-errors" "-Wno-deferred-out-of-scope-variables"
                          "-Wno-noncanonical-monad-instances"
                          "-Wno-noncanonical-monadfail-instances"
                          "-Wno-noncanonical-monoid-instances"
                          "-Wno-missing-pattern-synonym-signatures"
                          "-Wno-unrecognised-warning-flags"
                          "-Wno-simplifiable-class-constraints" "-Wno-cpp-undef"
                          "-Wno-unbanged-strict-patterns" "-Wno-missing-home-modules"
                          "-Wno-partial-fields" "-Wno-missing-export-lists"
                          "-Wno-inaccessible-code" "-Wno-star-is-type" "-Wno-star-binder"
                          "-Wno-implicit-kind-vars" "-Wno-missing-space-after-bang"
                          "-Wno-missing-deriving-strategies"
                          "-Wno-prepositive-qualified-module" "-Wno-unused-packages"
                          "-Wno-inferred-safe-imports" "-Wno-missing-safe-haskell-mode"
                          "-Wno-compat-unqualified-imports" "-Wno-deriving-defaults"
                          "-Wno-invalid-haddock" "-Wno-operator-whitespace-ext-conflict"
                          "-Wno-operator-whitespace" "-Wno-ambiguous-fields"
                          "-Wno-implicit-lift" "-Wno-missing-kind-signatures"
                          "-Wno-missing-poly-kind-signatures"
                          "-Wno-missing-exported-pattern-synonym-signatures"
                          "-Wno-redundant-strictness-flags" "-Wno-forall-identifier"
                          "-Wno-unicode-bidirectional-format-characters"
                          "-Wno-gadt-mono-local-binds" "-Wno-type-equality-out-of-scope"
                          "-Wno-type-equality-requires-operators" "-Wno-loopy-superclass-solve"
                          "-Wno-term-variable-capture" "-Wno-missing-role-annotations"
                          "-Wno-implicit-rhs-quantification" "-Wno-incomplete-export-warnings"
                          "-Wno-incomplete-record-selectors" "-Wno-badly-levelled-types"
                          "-Wno-badly-staged-types" "-Wno-inconsistent-flags"
                          "-Wno-data-kinds-tc" "-Wno-defaulted-exception-context"
                          "-Wno-view-pattern-signatures" "-Wno-useless-specialisations"
                          "-Wno-useless-specializations" "-Wno-deprecated-pragmas"
                          "-Wno-rule-lhs-equalities" "-Wno-unusable-unpack-pragmas"
                          "-Wno-pattern-namespace-specifier" "-Werror=duplicate-exports"
                          "-Werror=duplicate-constraints" "-Werror=redundant-constraints"
                          "-Werror=hi-shadowing" "-Werror=implicit-prelude"
                          "-Werror=incomplete-patterns" "-Werror=incomplete-uni-patterns"
                          "-Werror=incomplete-record-updates" "-Werror=overflowed-literals"
                          "-Werror=empty-enumerations" "-Werror=missing-fields"
                          "-Werror=missing-import-lists" "-Werror=missing-methods"
                          "-Werror=missing-signatures" "-Werror=missing-local-sigs"
                          "-Werror=missing-local-signatures" "-Werror=name-shadowing"
                          "-Werror=overlapping-patterns" "-Werror=type-defaults"
                          "-Werror=monomorphism-restriction" "-Werror=unused-top-binds"
                          "-Werror=unused-local-binds" "-Werror=unused-pattern-binds"
                          "-Werror=unused-imports" "-Werror=unused-matches"
                          "-Werror=unused-type-patterns" "-Werror=unused-foralls"
                          "-Werror=unused-record-wildcards" "-Werror=redundant-bang-patterns"
                          "-Werror=redundant-record-wildcards" "-Werror=deprecated-flags"
                          "-Werror=missing-monadfail-instances" "-Werror=semigroup"
                          "-Werror=dodgy-exports" "-Werror=dodgy-imports" "-Werror=orphans"
                          "-Werror=auto-orphans" "-Werror=identities" "-Werror=tabs"
                          "-Werror=unrecognised-pragmas" "-Werror=misplaced-pragmas"
                          "-Werror=dodgy-foreign-imports" "-Werror=unused-do-bind"
                          "-Werror=wrong-do-bind"
                          "-Werror=alternative-layout-rule-transitional" "-Werror=unsafe"
                          "-Werror=safe" "-Werror=trustworthy-safe"
                          "-Werror=missed-specialisations" "-Werror=missed-specializations"
                          "-Werror=all-missed-specialisations"
                          "-Werror=all-missed-specializations"
                          "-Werror=unsupported-calling-conventions"
                          "-Werror=unsupported-llvm-version" "-Werror=missed-extra-shared-lib"
                          "-Werror=inline-rule-shadowing" "-Werror=typed-holes"
                          "-Werror=partial-type-signatures" "-Werror=missing-exported-sigs"
                          "-Werror=missing-exported-signatures"
                          "-Werror=unticked-promoted-constructors" "-Werror=deriving-typeable"
                          "-Werror=deferred-type-errors"
                          "-Werror=deferred-out-of-scope-variables"
                          "-Werror=noncanonical-monad-instances"
                          "-Werror=noncanonical-monadfail-instances"
                          "-Werror=noncanonical-monoid-instances"
                          "-Werror=missing-pattern-synonym-signatures"
                          "-Werror=unrecognised-warning-flags"
                          "-Werror=simplifiable-class-constraints" "-Werror=cpp-undef"
                          "-Werror=unbanged-strict-patterns" "-Werror=missing-home-modules"
                          "-Werror=partial-fields" "-Werror=missing-export-lists"
                          "-Werror=inaccessible-code" "-Werror=star-is-type"
                          "-Werror=star-binder" "-Werror=implicit-kind-vars"
                          "-Werror=missing-space-after-bang"
                          "-Werror=missing-deriving-strategies"
                          "-Werror=prepositive-qualified-module" "-Werror=unused-packages"
                          "-Werror=inferred-safe-imports" "-Werror=missing-safe-haskell-mode"
                          "-Werror=compat-unqualified-imports" "-Werror=deriving-defaults"
                          "-Werror=invalid-haddock" "-Werror=operator-whitespace-ext-conflict"
                          "-Werror=operator-whitespace" "-Werror=ambiguous-fields"
                          "-Werror=implicit-lift" "-Werror=missing-kind-signatures"
                          "-Werror=missing-poly-kind-signatures"
                          "-Werror=missing-exported-pattern-synonym-signatures"
                          "-Werror=redundant-strictness-flags" "-Werror=forall-identifier"
                          "-Werror=unicode-bidirectional-format-characters"
                          "-Werror=gadt-mono-local-binds" "-Werror=type-equality-out-of-scope"
                          "-Werror=type-equality-requires-operators"
                          "-Werror=loopy-superclass-solve" "-Werror=term-variable-capture"
                          "-Werror=missing-role-annotations"
                          "-Werror=implicit-rhs-quantification"
                          "-Werror=incomplete-export-warnings"
                          "-Werror=incomplete-record-selectors" "-Werror=badly-levelled-types"
                          "-Werror=badly-staged-types" "-Werror=inconsistent-flags"
                          "-Werror=data-kinds-tc" "-Werror=defaulted-exception-context"
                          "-Werror=view-pattern-signatures" "-Werror=useless-specialisations"
                          "-Werror=useless-specializations" "-Werror=deprecated-pragmas"
                          "-Werror=rule-lhs-equalities" "-Werror=unusable-unpack-pragmas"
                          "-Werror=pattern-namespace-specifier" "-Wwarn=duplicate-exports"
                          "-Wwarn=duplicate-constraints" "-Wwarn=redundant-constraints"
                          "-Wwarn=hi-shadowing" "-Wwarn=implicit-prelude"
                          "-Wwarn=incomplete-patterns" "-Wwarn=incomplete-uni-patterns"
                          "-Wwarn=incomplete-record-updates" "-Wwarn=overflowed-literals"
                          "-Wwarn=empty-enumerations" "-Wwarn=missing-fields"
                          "-Wwarn=missing-import-lists" "-Wwarn=missing-methods"
                          "-Wwarn=missing-signatures" "-Wwarn=missing-local-sigs"
                          "-Wwarn=missing-local-signatures" "-Wwarn=name-shadowing"
                          "-Wwarn=overlapping-patterns" "-Wwarn=type-defaults"
                          "-Wwarn=monomorphism-restriction" "-Wwarn=unused-top-binds"
                          "-Wwarn=unused-local-binds" "-Wwarn=unused-pattern-binds"
                          "-Wwarn=unused-imports" "-Wwarn=unused-matches"
                          "-Wwarn=unused-type-patterns" "-Wwarn=unused-foralls"
                          "-Wwarn=unused-record-wildcards" "-Wwarn=redundant-bang-patterns"
                          "-Wwarn=redundant-record-wildcards" "-Wwarn=deprecated-flags"
                          "-Wwarn=missing-monadfail-instances" "-Wwarn=semigroup"
                          "-Wwarn=dodgy-exports" "-Wwarn=dodgy-imports" "-Wwarn=orphans"
                          "-Wwarn=auto-orphans" "-Wwarn=identities" "-Wwarn=tabs"
                          "-Wwarn=unrecognised-pragmas" "-Wwarn=misplaced-pragmas"
                          "-Wwarn=dodgy-foreign-imports" "-Wwarn=unused-do-bind"
                          "-Wwarn=wrong-do-bind" "-Wwarn=alternative-layout-rule-transitional"
                          "-Wwarn=unsafe" "-Wwarn=safe" "-Wwarn=trustworthy-safe"
                          "-Wwarn=missed-specialisations" "-Wwarn=missed-specializations"
                          "-Wwarn=all-missed-specialisations"
                          "-Wwarn=all-missed-specializations"
                          "-Wwarn=unsupported-calling-conventions"
                          "-Wwarn=unsupported-llvm-version" "-Wwarn=missed-extra-shared-lib"
                          "-Wwarn=inline-rule-shadowing" "-Wwarn=typed-holes"
                          "-Wwarn=partial-type-signatures" "-Wwarn=missing-exported-sigs"
                          "-Wwarn=missing-exported-signatures"
                          "-Wwarn=unticked-promoted-constructors" "-Wwarn=deriving-typeable"
                          "-Wwarn=deferred-type-errors"
                          "-Wwarn=deferred-out-of-scope-variables"
                          "-Wwarn=noncanonical-monad-instances"
                          "-Wwarn=noncanonical-monadfail-instances"
                          "-Wwarn=noncanonical-monoid-instances"
                          "-Wwarn=missing-pattern-synonym-signatures"
                          "-Wwarn=unrecognised-warning-flags"
                          "-Wwarn=simplifiable-class-constraints" "-Wwarn=cpp-undef"
                          "-Wwarn=unbanged-strict-patterns" "-Wwarn=missing-home-modules"
                          "-Wwarn=partial-fields" "-Wwarn=missing-export-lists"
                          "-Wwarn=inaccessible-code" "-Wwarn=star-is-type" "-Wwarn=star-binder"
                          "-Wwarn=implicit-kind-vars" "-Wwarn=missing-space-after-bang"
                          "-Wwarn=missing-deriving-strategies"
                          "-Wwarn=prepositive-qualified-module" "-Wwarn=unused-packages"
                          "-Wwarn=inferred-safe-imports" "-Wwarn=missing-safe-haskell-mode"
                          "-Wwarn=compat-unqualified-imports" "-Wwarn=deriving-defaults"
                          "-Wwarn=invalid-haddock" "-Wwarn=operator-whitespace-ext-conflict"
                          "-Wwarn=operator-whitespace" "-Wwarn=ambiguous-fields"
                          "-Wwarn=implicit-lift" "-Wwarn=missing-kind-signatures"
                          "-Wwarn=missing-poly-kind-signatures"
                          "-Wwarn=missing-exported-pattern-synonym-signatures"
                          "-Wwarn=redundant-strictness-flags" "-Wwarn=forall-identifier"
                          "-Wwarn=unicode-bidirectional-format-characters"
                          "-Wwarn=gadt-mono-local-binds" "-Wwarn=type-equality-out-of-scope"
                          "-Wwarn=type-equality-requires-operators"
                          "-Wwarn=loopy-superclass-solve" "-Wwarn=term-variable-capture"
                          "-Wwarn=missing-role-annotations"
                          "-Wwarn=implicit-rhs-quantification"
                          "-Wwarn=incomplete-export-warnings"
                          "-Wwarn=incomplete-record-selectors" "-Wwarn=badly-levelled-types"
                          "-Wwarn=badly-staged-types" "-Wwarn=inconsistent-flags"
                          "-Wwarn=data-kinds-tc" "-Wwarn=defaulted-exception-context"
                          "-Wwarn=view-pattern-signatures" "-Wwarn=useless-specialisations"
                          "-Wwarn=useless-specializations" "-Wwarn=deprecated-pragmas"
                          "-Wwarn=rule-lhs-equalities" "-Wwarn=unusable-unpack-pragmas"
                          "-Wwarn=pattern-namespace-specifier" "-Wno-error=duplicate-exports"
                          "-Wno-error=duplicate-constraints" "-Wno-error=redundant-constraints"
                          "-Wno-error=hi-shadowing" "-Wno-error=implicit-prelude"
                          "-Wno-error=incomplete-patterns" "-Wno-error=incomplete-uni-patterns"
                          "-Wno-error=incomplete-record-updates"
                          "-Wno-error=overflowed-literals" "-Wno-error=empty-enumerations"
                          "-Wno-error=missing-fields" "-Wno-error=missing-import-lists"
                          "-Wno-error=missing-methods" "-Wno-error=missing-signatures"
                          "-Wno-error=missing-local-sigs" "-Wno-error=missing-local-signatures"
                          "-Wno-error=name-shadowing" "-Wno-error=overlapping-patterns"
                          "-Wno-error=type-defaults" "-Wno-error=monomorphism-restriction"
                          "-Wno-error=unused-top-binds" "-Wno-error=unused-local-binds"
                          "-Wno-error=unused-pattern-binds" "-Wno-error=unused-imports"
                          "-Wno-error=unused-matches" "-Wno-error=unused-type-patterns"
                          "-Wno-error=unused-foralls" "-Wno-error=unused-record-wildcards"
                          "-Wno-error=redundant-bang-patterns"
                          "-Wno-error=redundant-record-wildcards" "-Wno-error=deprecated-flags"
                          "-Wno-error=missing-monadfail-instances" "-Wno-error=semigroup"
                          "-Wno-error=dodgy-exports" "-Wno-error=dodgy-imports"
                          "-Wno-error=orphans" "-Wno-error=auto-orphans"
                          "-Wno-error=identities" "-Wno-error=tabs"
                          "-Wno-error=unrecognised-pragmas" "-Wno-error=misplaced-pragmas"
                          "-Wno-error=dodgy-foreign-imports" "-Wno-error=unused-do-bind"
                          "-Wno-error=wrong-do-bind"
                          "-Wno-error=alternative-layout-rule-transitional" "-Wno-error=unsafe"
                          "-Wno-error=safe" "-Wno-error=trustworthy-safe"
                          "-Wno-error=missed-specialisations"
                          "-Wno-error=missed-specializations"
                          "-Wno-error=all-missed-specialisations"
                          "-Wno-error=all-missed-specializations"
                          "-Wno-error=unsupported-calling-conventions"
                          "-Wno-error=unsupported-llvm-version"
                          "-Wno-error=missed-extra-shared-lib"
                          "-Wno-error=inline-rule-shadowing" "-Wno-error=typed-holes"
                          "-Wno-error=partial-type-signatures"
                          "-Wno-error=missing-exported-sigs"
                          "-Wno-error=missing-exported-signatures"
                          "-Wno-error=unticked-promoted-constructors"
                          "-Wno-error=deriving-typeable" "-Wno-error=deferred-type-errors"
                          "-Wno-error=deferred-out-of-scope-variables"
                          "-Wno-error=noncanonical-monad-instances"
                          "-Wno-error=noncanonical-monadfail-instances"
                          "-Wno-error=noncanonical-monoid-instances"
                          "-Wno-error=missing-pattern-synonym-signatures"
                          "-Wno-error=unrecognised-warning-flags"
                          "-Wno-error=simplifiable-class-constraints" "-Wno-error=cpp-undef"
                          "-Wno-error=unbanged-strict-patterns"
                          "-Wno-error=missing-home-modules" "-Wno-error=partial-fields"
                          "-Wno-error=missing-export-lists" "-Wno-error=inaccessible-code"
                          "-Wno-error=star-is-type" "-Wno-error=star-binder"
                          "-Wno-error=implicit-kind-vars" "-Wno-error=missing-space-after-bang"
                          "-Wno-error=missing-deriving-strategies"
                          "-Wno-error=prepositive-qualified-module"
                          "-Wno-error=unused-packages" "-Wno-error=inferred-safe-imports"
                          "-Wno-error=missing-safe-haskell-mode"
                          "-Wno-error=compat-unqualified-imports"
                          "-Wno-error=deriving-defaults" "-Wno-error=invalid-haddock"
                          "-Wno-error=operator-whitespace-ext-conflict"
                          "-Wno-error=operator-whitespace" "-Wno-error=ambiguous-fields"
                          "-Wno-error=implicit-lift" "-Wno-error=missing-kind-signatures"
                          "-Wno-error=missing-poly-kind-signatures"
                          "-Wno-error=missing-exported-pattern-synonym-signatures"
                          "-Wno-error=redundant-strictness-flags"
                          "-Wno-error=forall-identifier"
                          "-Wno-error=unicode-bidirectional-format-characters"
                          "-Wno-error=gadt-mono-local-binds"
                          "-Wno-error=type-equality-out-of-scope"
                          "-Wno-error=type-equality-requires-operators"
                          "-Wno-error=loopy-superclass-solve"
                          "-Wno-error=term-variable-capture"
                          "-Wno-error=missing-role-annotations"
                          "-Wno-error=implicit-rhs-quantification"
                          "-Wno-error=incomplete-export-warnings"
                          "-Wno-error=incomplete-record-selectors"
                          "-Wno-error=badly-levelled-types" "-Wno-error=badly-staged-types"
                          "-Wno-error=inconsistent-flags" "-Wno-error=data-kinds-tc"
                          "-Wno-error=defaulted-exception-context"
                          "-Wno-error=view-pattern-signatures"
                          "-Wno-error=useless-specialisations"
                          "-Wno-error=useless-specializations" "-Wno-error=deprecated-pragmas"
                          "-Wno-error=rule-lhs-equalities" "-Wno-error=unusable-unpack-pragmas"
                          "-Wno-error=pattern-namespace-specifier" "-Wwarnings-deprecations"
                          "-Wno-warnings-deprecations" "-Werror=warnings-deprecations"
                          "-Wwarn=warnings-deprecations" "-Wno-error=warnings-deprecations"
                          "-ddisable-js-minifier" "-ddisable-js-c-sources" "-fth" "-ffi"
                          "-fffi" "-farrows" "-fimplicit-prelude" "-fbang-patterns"
                          "-fmonomorphism-restriction" "-fextended-default-rules"
                          "-fimplicit-params" "-fscoped-type-variables"
                          "-fallow-overlapping-instances" "-fallow-undecidable-instances"
                          "-fallow-incoherent-instances" "-fno-th" "-fno-fi" "-fno-ffi"
                          "-fno-arrows" "-fno-implicit-prelude" "-fno-bang-patterns"
                          "-fno-monomorphism-restriction" "-fno-extended-default-rules"
                          "-fno-implicit-params" "-fno-scoped-type-variables"
                          "-fno-allow-overlapping-instances" "-fno-allow-undecidable-instances"
                          "-fno-allow-incoherent-instances" "-XCPP" "-XOverlappingInstances"
                          "-XUndecidableInstances" "-XIncoherentInstances"
                          "-XUndecidableSuperClasses" "-XMonomorphismRestriction"
                          "-XMonoLocalBinds" "-XDeepSubsumption" "-XRelaxedPolyRec"
                          "-XExtendedDefaultRules" "-XNamedDefaults"
                          "-XForeignFunctionInterface" "-XUnliftedFFITypes"
                          "-XInterruptibleFFI" "-XCApiFFI" "-XGHCForeignImportPrim"
                          "-XJavaScriptFFI" "-XParallelArrays" "-XArrows" "-XTemplateHaskell"
                          "-XTemplateHaskellQuotes" "-XQualifiedDo" "-XQuasiQuotes"
                          "-XImplicitParams" "-XImplicitPrelude" "-XScopedTypeVariables"
                          "-XPatternSignatures" "-XAllowAmbiguousTypes" "-XUnboxedTuples"
                          "-XUnboxedSums" "-XUnliftedNewtypes" "-XUnliftedDatatypes"
                          "-XBangPatterns" "-XTypeFamilies" "-XTypeFamilyDependencies"
                          "-XTypeInType" "-XOverloadedStrings" "-XOverloadedLists"
                          "-XNumDecimals" "-XDisambiguateRecordFields" "-XRecordWildCards"
                          "-XNamedFieldPuns" "-XRecordPuns" "-XViewPatterns" "-XOrPatterns"
                          "-XGADTs" "-XGADTSyntax" "-XNPlusKPatterns" "-XDoAndIfThenElse"
                          "-XBlockArguments" "-XRebindableSyntax" "-XConstraintKinds"
                          "-XPolyKinds" "-XDataKinds" "-XTypeData" "-XInstanceSigs"
                          "-XApplicativeDo" "-XLinearTypes" "-XRequiredTypeArguments"
                          "-XStandaloneDeriving" "-XDeriveDataTypeable" "-XAutoDeriveTypeable"
                          "-XDeriveFunctor" "-XDeriveTraversable" "-XDeriveFoldable"
                          "-XDeriveGeneric" "-XDefaultSignatures" "-XDeriveAnyClass"
                          "-XDeriveLift" "-XDerivingStrategies" "-XDerivingVia"
                          "-XTypeSynonymInstances" "-XFlexibleContexts" "-XFlexibleInstances"
                          "-XConstrainedClassMethods" "-XMultiParamTypeClasses"
                          "-XNullaryTypeClasses" "-XFunctionalDependencies" "-XUnicodeSyntax"
                          "-XExistentialQuantification" "-XMagicHash" "-XEmptyDataDecls"
                          "-XKindSignatures" "-XRoleAnnotations" "-XParallelListComp"
                          "-XTransformListComp" "-XMonadComprehensions"
                          "-XGeneralizedNewtypeDeriving" "-XGeneralisedNewtypeDeriving"
                          "-XRecursiveDo" "-XDoRec" "-XPostfixOperators" "-XTupleSections"
                          "-XPatternGuards" "-XLiberalTypeSynonyms" "-XRankNTypes"
                          "-XRank2Types" "-XPolymorphicComponents" "-XImpredicativeTypes"
                          "-XTypeOperators" "-XExplicitNamespaces" "-XPackageImports"
                          "-XExplicitForAll" "-XAlternativeLayoutRule"
                          "-XAlternativeLayoutRuleTransitional" "-XDatatypeContexts"
                          "-XNondecreasingIndentation" "-XRelaxedLayout"
                          "-XTraditionalRecordSyntax" "-XLambdaCase" "-XMultiWayIf"
                          "-XBinaryLiterals" "-XNegativeLiterals" "-XHexFloatLiterals"
                          "-XDuplicateRecordFields" "-XOverloadedLabels" "-XEmptyCase"
                          "-XPatternSynonyms" "-XPartialTypeSignatures" "-XNamedWildCards"
                          "-XStaticPointers" "-XTypeApplications" "-XStrict" "-XStrictData"
                          "-XEmptyDataDeriving" "-XNumericUnderscores"
                          "-XQuantifiedConstraints" "-XStarIsType" "-XImportQualifiedPost"
                          "-XCUSKs" "-XStandaloneKindSignatures" "-XLexicalNegation"
                          "-XFieldSelectors" "-XOverloadedRecordDot" "-XOverloadedRecordUpdate"
                          "-XTypeAbstractions" "-XExtendedLiterals" "-XListTuplePuns"
                          "-XMultilineStrings" "-XExplicitLevelImports"
                          "-XImplicitStagePersistence" "-XNoCPP" "-XNoOverlappingInstances"
                          "-XNoUndecidableInstances" "-XNoIncoherentInstances"
                          "-XNoUndecidableSuperClasses" "-XNoMonomorphismRestriction"
                          "-XNoMonoLocalBinds" "-XNoDeepSubsumption" "-XNoRelaxedPolyRec"
                          "-XNoExtendedDefaultRules" "-XNoNamedDefaults"
                          "-XNoForeignFunctionInterface" "-XNoUnliftedFFITypes"
                          "-XNoInterruptibleFFI" "-XNoCApiFFI" "-XNoGHCForeignImportPrim"
                          "-XNoJavaScriptFFI" "-XNoParallelArrays" "-XNoArrows"
                          "-XNoTemplateHaskell" "-XNoTemplateHaskellQuotes" "-XNoQualifiedDo"
                          "-XNoQuasiQuotes" "-XNoImplicitParams" "-XNoImplicitPrelude"
                          "-XNoScopedTypeVariables" "-XNoPatternSignatures"
                          "-XNoAllowAmbiguousTypes" "-XNoUnboxedTuples" "-XNoUnboxedSums"
                          "-XNoUnliftedNewtypes" "-XNoUnliftedDatatypes" "-XNoBangPatterns"
                          "-XNoTypeFamilies" "-XNoTypeFamilyDependencies" "-XNoTypeInType"
                          "-XNoOverloadedStrings" "-XNoOverloadedLists" "-XNoNumDecimals"
                          "-XNoDisambiguateRecordFields" "-XNoRecordWildCards"
                          "-XNoNamedFieldPuns" "-XNoRecordPuns" "-XNoViewPatterns"
                          "-XNoOrPatterns" "-XNoGADTs" "-XNoGADTSyntax" "-XNoNPlusKPatterns"
                          "-XNoDoAndIfThenElse" "-XNoBlockArguments" "-XNoRebindableSyntax"
                          "-XNoConstraintKinds" "-XNoPolyKinds" "-XNoDataKinds" "-XNoTypeData"
                          "-XNoInstanceSigs" "-XNoApplicativeDo" "-XNoLinearTypes"
                          "-XNoRequiredTypeArguments" "-XNoStandaloneDeriving"
                          "-XNoDeriveDataTypeable" "-XNoAutoDeriveTypeable" "-XNoDeriveFunctor"
                          "-XNoDeriveTraversable" "-XNoDeriveFoldable" "-XNoDeriveGeneric"
                          "-XNoDefaultSignatures" "-XNoDeriveAnyClass" "-XNoDeriveLift"
                          "-XNoDerivingStrategies" "-XNoDerivingVia" "-XNoTypeSynonymInstances"
                          "-XNoFlexibleContexts" "-XNoFlexibleInstances"
                          "-XNoConstrainedClassMethods" "-XNoMultiParamTypeClasses"
                          "-XNoNullaryTypeClasses" "-XNoFunctionalDependencies"
                          "-XNoUnicodeSyntax" "-XNoExistentialQuantification" "-XNoMagicHash"
                          "-XNoEmptyDataDecls" "-XNoKindSignatures" "-XNoRoleAnnotations"
                          "-XNoParallelListComp" "-XNoTransformListComp"
                          "-XNoMonadComprehensions" "-XNoGeneralizedNewtypeDeriving"
                          "-XNoGeneralisedNewtypeDeriving" "-XNoRecursiveDo" "-XNoDoRec"
                          "-XNoPostfixOperators" "-XNoTupleSections" "-XNoPatternGuards"
                          "-XNoLiberalTypeSynonyms" "-XNoRankNTypes" "-XNoRank2Types"
                          "-XNoPolymorphicComponents" "-XNoImpredicativeTypes"
                          "-XNoTypeOperators" "-XNoExplicitNamespaces" "-XNoPackageImports"
                          "-XNoExplicitForAll" "-XNoAlternativeLayoutRule"
                          "-XNoAlternativeLayoutRuleTransitional" "-XNoDatatypeContexts"
                          "-XNoNondecreasingIndentation" "-XNoRelaxedLayout"
                          "-XNoTraditionalRecordSyntax" "-XNoLambdaCase" "-XNoMultiWayIf"
                          "-XNoBinaryLiterals" "-XNoNegativeLiterals" "-XNoHexFloatLiterals"
                          "-XNoDuplicateRecordFields" "-XNoOverloadedLabels" "-XNoEmptyCase"
                          "-XNoPatternSynonyms" "-XNoPartialTypeSignatures"
                          "-XNoNamedWildCards" "-XNoStaticPointers" "-XNoTypeApplications"
                          "-XNoStrict" "-XNoStrictData" "-XNoEmptyDataDeriving"
                          "-XNoNumericUnderscores" "-XNoQuantifiedConstraints" "-XNoStarIsType"
                          "-XNoImportQualifiedPost" "-XNoCUSKs" "-XNoStandaloneKindSignatures"
                          "-XNoLexicalNegation" "-XNoFieldSelectors" "-XNoOverloadedRecordDot"
                          "-XNoOverloadedRecordUpdate" "-XNoTypeAbstractions"
                          "-XNoExtendedLiterals" "-XNoListTuplePuns" "-XNoMultilineStrings"
                          "-XNoExplicitLevelImports" "-XNoImplicitStagePersistence"
                          "-XHaskell98" "-XHaskell2010" "-XGHC2021" "-XGHC2024" "-XUnsafe"
                          "-XTrustworthy" "-XSafe" "-?" "--help" "-V" "--version"
                          "--numeric-version" "--info" "--show-options" "--supported-languages"
                          "--supported-extensions" "--show-packages" "--print-project-version"
                          "--print-project-git-commit-id" "--print-booter-version"
                          "--print-stage" "--print-build-platform" "--print-host-platform"
                          "--print-target-platform" "--print-have-interpreter"
                          "--print-object-splitting-supported"
                          "--print-have-native-code-generator" "--print-support-smp"
                          "--print-unregisterised" "--print-tables-next-to-code"
                          "--print-rts-ways" "--print-leading-underscore" "--print-debug-on"
                          "--print-libdir" "--print-global-package-db"
                          "--print-c-compiler-flags" "--print-c-compiler-link-flags"
                          "--show-iface" "-c" "-M" "-E" "-C" "-S" "--run" "--make" "-unit"
                          "--backpack" "--interactive" "--abi-hash" "-e" "--frontend")
                         ))))))

;;;###autoload (autoload 'pcomplete/ghc "shell-completion-ghc" nil t)
(defpcmpl pcomplete/ghc
  `(opts
    (flags ,@pcomplete-ghc-flags)
    (args (pcmpl-haskell-source-or-obj-files)))
  :evaluate-definition t)

(provide 'shell-completion-ghc)

;; Local Variables:
;; End:

;; shell-completion-ghc.el ends here
