;;; solarized-palettes.el --- solarized palettes   -*- lexical-binding: t -*-

;; Copyright (C) 2011-2021 Bozhidar Batsov

;; Author: Bozhidar Batsov <bozhidar@batsov.dev>
;; Author: Thomas Frössman <thomasf@jossystem.se>

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file only contains data which is lists of colors of some sort,
;; there is also code that generates palettes in solarized.el.  That
;; code does not belong here.

;;; Code:

(eval-when-compile
  (require 'cl))

(cl-defstruct (solarized-palette
               (:constructor make--solarized-palette)
               (:copier nil))
  mode ;; Either 'dark or 'light, for Emacs.

  background
  background-highlights
  secondary-content
  aux-mid
  primary-content
  emphasized-content
  aux-high-1
  aux-high-2

  red
  orange
  yellow
  green
  cyan
  blue
  violet
  magenta

  red-aux-fg
  orange-aux-fg
  yellow-aux-fg
  green-aux-fg
  cyan-aux-fg
  blue-aux-fg
  violet-aux-fg
  magenta-aux-fg

  red-aux-bg
  orange-aux-bg
  yellow-aux-bg
  green-aux-bg
  cyan-aux-bg
  blue-aux-bg
  violet-aux-bg
  magenta-aux-bg

  red-aux-aux-fg
  orange-aux-aux-fg
  yellow-aux-aux-fg
  green-aux-aux-fg
  cyan-aux-aux-fg
  blue-aux-aux-fg
  violet-aux-aux-fg
  magenta-aux-aux-fg

  red-aux-aux-bg
  orange-aux-aux-bg
  yellow-aux-aux-bg
  green-aux-aux-bg
  cyan-aux-aux-bg
  blue-aux-aux-bg
  violet-aux-aux-bg
  magenta-aux-aux-bg

  red-aux-aux-aux-fg
  orange-aux-aux-aux-fg
  yellow-aux-aux-aux-fg
  green-aux-aux-aux-fg
  cyan-aux-aux-aux-fg
  blue-aux-aux-aux-fg
  violet-aux-aux-aux-fg
  magenta-aux-aux-aux-fg

  red-aux-aux-aux-bg
  orange-aux-aux-aux-bg
  yellow-aux-aux-aux-bg
  green-aux-aux-aux-bg
  cyan-aux-aux-aux-bg
  blue-aux-aux-aux-bg
  violet-aux-aux-aux-bg
  magenta-aux-aux-aux-bg)

(defsubst num->color (x)
  (format "#%06x" x))

(eval-when-compile
  (defun solarized-get-color (key xs)
    (declare (pure t) (side-effect-free nil))
    (aif (assq key xs)
        (progn
          (cl-assert (fixnump (cdr it))
                     "Color is not a number: %s" (car it))
          (cdr it))
      (error "Key not found: %s" key)))

  (defun make-solarized-palette (light? palette)
    (declare (pure t) (side-effect-free t))
    (make--solarized-palette
     :mode                      (if light? 'light 'dark)

     :background                (solarized-get-color (if light? 'base3 'base03) palette)
     :background-highlights     (solarized-get-color (if light? 'base2 'base02) palette)
     :secondary-content         (solarized-get-color (if light? 'base1 'base01) palette)
     :aux-mid                   (solarized-get-color (if light? 'base0 'base00) palette)
     :primary-content           (solarized-get-color (if light? 'base00 'base0) palette)
     :emphasized-content        (solarized-get-color (if light? 'base01 'base1) palette)
     :aux-high-1                (solarized-get-color (if light? 'base02 'base2) palette)
     :aux-high-2                (solarized-get-color (if light? 'base03 'base3) palette)

     :red                       (solarized-get-color 'red     palette)
     :orange                    (solarized-get-color 'orange  palette)
     :yellow                    (solarized-get-color 'yellow  palette)
     :green                     (solarized-get-color 'green   palette)
     :cyan                      (solarized-get-color 'cyan    palette)
     :blue                      (solarized-get-color 'blue    palette)
     :violet                    (solarized-get-color 'violet  palette)
     :magenta                   (solarized-get-color 'magenta palette)

     :red-aux-fg                (solarized-get-color (if light? 'red-d     'red-l)     palette)
     :orange-aux-fg             (solarized-get-color (if light? 'orange-d  'orange-l)  palette)
     :yellow-aux-fg             (solarized-get-color (if light? 'yellow-d  'yellow-l)  palette)
     :green-aux-fg              (solarized-get-color (if light? 'green-d   'green-l)   palette)
     :cyan-aux-fg               (solarized-get-color (if light? 'cyan-d    'cyan-l)    palette)
     :blue-aux-fg               (solarized-get-color (if light? 'blue-d    'blue-l)    palette)
     :violet-aux-fg             (solarized-get-color (if light? 'violet-d  'violet-l)  palette)
     :magenta-aux-fg            (solarized-get-color (if light? 'magenta-d 'magenta-l) palette)

     :red-aux-bg                (solarized-get-color (if light? 'red-l     'red-d)     palette)
     :orange-aux-bg             (solarized-get-color (if light? 'orange-l  'orange-d)  palette)
     :yellow-aux-bg             (solarized-get-color (if light? 'yellow-l  'yellow-d)  palette)
     :green-aux-bg              (solarized-get-color (if light? 'green-l   'green-d)   palette)
     :cyan-aux-bg               (solarized-get-color (if light? 'cyan-l    'cyan-d)    palette)
     :blue-aux-bg               (solarized-get-color (if light? 'blue-l    'blue-d)    palette)
     :violet-aux-bg             (solarized-get-color (if light? 'violet-l  'violet-d)  palette)
     :magenta-aux-bg            (solarized-get-color (if light? 'magenta-l 'magenta-d) palette)

     :red-aux-aux-fg            (solarized-get-color 'red-1fg     palette)
     :orange-aux-aux-fg         (solarized-get-color 'orange-1fg  palette)
     :yellow-aux-aux-fg         (solarized-get-color 'yellow-1fg  palette)
     :green-aux-aux-fg          (solarized-get-color 'green-1fg   palette)
     :cyan-aux-aux-fg           (solarized-get-color 'cyan-1fg    palette)
     :blue-aux-aux-fg           (solarized-get-color 'blue-1fg    palette)
     :violet-aux-aux-fg         (solarized-get-color 'violet-1fg  palette)
     :magenta-aux-aux-fg        (solarized-get-color 'magenta-1fg palette)

     :red-aux-aux-bg            (solarized-get-color 'red-1bg     palette)
     :orange-aux-aux-bg         (solarized-get-color 'orange-1bg  palette)
     :yellow-aux-aux-bg         (solarized-get-color 'yellow-1bg  palette)
     :green-aux-aux-bg          (solarized-get-color 'green-1bg   palette)
     :cyan-aux-aux-bg           (solarized-get-color 'cyan-1bg    palette)
     :blue-aux-aux-bg           (solarized-get-color 'blue-1bg    palette)
     :violet-aux-aux-bg         (solarized-get-color 'violet-1bg  palette)
     :magenta-aux-aux-bg        (solarized-get-color 'magenta-1bg palette)

     :red-aux-aux-aux-fg        (solarized-get-color 'red-2fg     palette)
     :orange-aux-aux-aux-fg     (solarized-get-color 'orange-2fg  palette)
     :yellow-aux-aux-aux-fg     (solarized-get-color 'yellow-2fg  palette)
     :green-aux-aux-aux-fg      (solarized-get-color 'green-2fg   palette)
     :cyan-aux-aux-aux-fg       (solarized-get-color 'cyan-2fg    palette)
     :blue-aux-aux-aux-fg       (solarized-get-color 'blue-2fg    palette)
     :violet-aux-aux-aux-fg     (solarized-get-color 'violet-2fg  palette)
     :magenta-aux-aux-aux-fg    (solarized-get-color 'magenta-2fg palette)

     ;; :red-aux-aux-aux-bg

     :red-aux-aux-aux-bg        (solarized-get-color 'red-2bg     palette)
     :orange-aux-aux-aux-bg     (solarized-get-color 'orange-2bg  palette)
     :yellow-aux-aux-aux-bg     (solarized-get-color 'yellow-2bg  palette)
     :green-aux-aux-aux-bg      (solarized-get-color 'green-2bg   palette)
     :cyan-aux-aux-aux-bg       (solarized-get-color 'cyan-2bg    palette)
     :blue-aux-aux-aux-bg       (solarized-get-color 'blue-2bg    palette)
     :violet-aux-aux-aux-bg     (solarized-get-color 'violet-2bg  palette)
     :magenta-aux-aux-aux-bg    (solarized-get-color 'magenta-2bg palette))))

;; Each color is 3 bytes so we’re good
(defconst solarized-dark-color-palette
  (eval-when-compile
    (make-solarized-palette
     nil
     '(;; solarized-dark palette
       (base03      . #x002b36)
       (base02      . #x073642)
       (base01      . #x586e75)
       (base00      . #x657b83)
       (base0       . #x839496)
       (base1       . #x93a1a1)
       (base2       . #xeee8d5)
       (base3       . #xfdf6e3)
       (yellow      . #xb58900)
       (orange      . #xcb4b16)
       (red         . #xdc322f)
       (magenta     . #xd33682)
       (violet      . #x6c71c4)
       (blue        . #x268bd2)
       (cyan        . #x2aa198)
       (green       . #x859900)
       (yellow-1bg  . #x273532)
       (yellow-1fg  . #xaf8f41)
       (yellow-2bg  . #x433e20)
       (yellow-2fg  . #xb39a5e)
       (yellow-d    . #x866300)
       (yellow-l    . #xe1af4b)
       (orange-1bg  . #x2b2d2e)
       (orange-1fg  . #xca6f48)
       (orange-2bg  . #x4d2c1f)
       (orange-2fg  . #xc47c5d)
       (orange-d    . #x992700)
       (orange-l    . #xfb7640)
       (red-1bg     . #x2d2c31)
       (red-1fg     . #xd66556)
       (red-2bg     . #x532725)
       (red-2fg     . #xce7667)
       (red-d       . #xa7020a)
       (red-l       . #xff6849)
       (magenta-1bg . #x272d3c)
       (magenta-1fg . #xcc6791)
       (magenta-2bg . #x4c2942)
       (magenta-2fg . #xc47896)
       (magenta-d   . #xa00559)
       (magenta-l   . #xff699e)
       (violet-1bg  . #x0c3144)
       (violet-1fg  . #x8085c0)
       (violet-2bg  . #x1a365a)
       (violet-2fg  . #x888dbc)
       (violet-d    . #x243e9b)
       (violet-l    . #x8d85e7)
       (blue-1bg    . #x003547)
       (blue-1fg    . #x5c93c5)
       (blue-2bg    . #x003f5e)
       (blue-2fg    . #x709bc3)
       (blue-d      . #x0061a8)
       (blue-l      . #x74adf5)
       (cyan-1bg    . #x013841)
       (cyan-1fg    . #x54a099)
       (cyan-2bg    . #x00464a)
       (cyan-2fg    . #x6ba8a2)
       (cyan-d      . #x007d76)
       (cyan-l      . #x6ccec0)
       (green-1bg   . #x1d3732)
       (green-1fg   . #x8c9a43)
       (green-2bg   . #x2f4321)
       (green-2fg   . #x97a35f)
       (green-d     . #x5b7300)
       (green-l     . #xb3c34d)
       ;; palette end
       )))
  "The solarized color palette alist.")

(defconst solarized-light-color-palette
  (eval-when-compile
    (make-solarized-palette
     t
     '(;; solarized-light palette
       (base03      . #x002b36)
       (base02      . #x073642)
       (base01      . #x586e75)
       (base00      . #x657b83)
       (base0       . #x839496)
       (base1       . #x93a1a1)
       (base2       . #xeee8d5)
       (base3       . #xfdf6e3)
       (yellow      . #xb58900)
       (orange      . #xcb4b16)
       (red         . #xdc322f)
       (magenta     . #xd33682)
       (violet      . #x6c71c4)
       (blue        . #x268bd2)
       (cyan        . #x2aa198)
       (green       . #x859900)
       (yellow-1bg  . #xf8e8c6)
       (yellow-1fg  . #x876d26)
       (yellow-2bg  . #xf1d49b)
       (yellow-2fg  . #x766634)
       (yellow-d    . #x866300)
       (yellow-l    . #xe1af4b)
       (orange-1bg  . #xfedfc5)
       (orange-1fg  . #x974727)
       (orange-2bg  . #xffbd99)
       (orange-2fg  . #x854a33)
       (orange-d    . #x992700)
       (orange-l    . #xfb7640)
       (red-1bg     . #xffdec8)
       (red-1fg     . #xa33c35)
       (red-2bg     . #xffb9a1)
       (red-2fg     . #x8e433d)
       (red-d       . #xa7020a)
       (red-l       . #xff6849)
       (magenta-1bg . #xfdded7)
       (magenta-1fg . #x9a3f6c)
       (magenta-2bg . #xfdbac6)
       (magenta-2fg . #x854568)
       (magenta-d   . #xa00559)
       (magenta-l   . #xff699e)
       (violet-1bg  . #xebe4e2)
       (violet-1fg  . #x4f5e99)
       (violet-2bg  . #xd1c9e3)
       (violet-2fg  . #x475a8b)
       (violet-d    . #x243e9b)
       (violet-l    . #x8d85e7)
       (blue-1bg    . #xe7e8e4)
       (blue-1fg    . #x1e6fa2)
       (blue-2bg    . #xc3d5e9)
       (blue-2fg    . #x246792)
       (blue-d      . #x0061a8)
       (blue-l      . #x74adf5)
       (cyan-1bg    . #xe4ecda)
       (cyan-1fg    . #x207e7b)
       (cyan-2bg    . #xbedfcf)
       (cyan-2fg    . #x247374)
       (cyan-d      . #x007d76)
       (cyan-l      . #x6ccec0)
       (green-1bg   . #xefeac7)
       (green-1fg   . #x657827)
       (green-2bg   . #xdbdb9c)
       (green-2fg   . #x5b6e35)
       (green-d     . #x5b7300)
       (green-l     . #xb3c34d)
       ;; palette end
       )))
  "The solarized color palette alist.")

(defconst solarized-dark-high-contrast-palette
  (eval-when-compile
    (make-solarized-palette
     nil
     '(;; solarized-dark-high-contrast palette
       (base03      . #x002732)
       (base02      . #x01323d)
       (base01      . #x62787f)
       (base00      . #x60767e)
       (base0       . #x8d9fa1)
       (base1       . #x9eacac)
       (base2       . #xfaf3e0)
       (base3       . #xffffee)
       (yellow      . #xc49619)
       (orange      . #xdb5823)
       (red         . #xec423a)
       (magenta     . #xe2468f)
       (violet      . #x7a7ed2)
       (blue        . #x3c98e0)
       (cyan        . #x3cafa5)
       (green       . #x93a61a)
       (yellow-1bg  . #x273430)
       (yellow-1fg  . #xbb9a4c)
       (yellow-2bg  . #x484224)
       (yellow-2fg  . #xbba165)
       (yellow-d    . #x936d00)
       (yellow-l    . #xf3be51)
       (orange-1bg  . #x2d2d2f)
       (orange-1fg  . #xd0744d)
       (orange-2bg  . #x522f22)
       (orange-2fg  . #xcd8464)
       (orange-d    . #xa72e01)
       (orange-l    . #xff8148)
       (red-1bg     . #x2f2c31)
       (red-1fg     . #xdc6a5a)
       (red-2bg     . #x582b29)
       (red-2fg     . #xd77e6f)
       (red-d       . #xae1212)
       (red-l       . #xff7254)
       (magenta-1bg . #x292d3c)
       (magenta-1fg . #xd16c96)
       (magenta-2bg . #x512c46)
       (magenta-2fg . #xcd809f)
       (magenta-d   . #xa81761)
       (magenta-l   . #xff75ab)
       (violet-1bg  . #x103145)
       (violet-1fg  . #x8589c4)
       (violet-2bg  . #x213a5e)
       (violet-2fg  . #x9095c4)
       (violet-d    . #x3548a2)
       (violet-l    . #x9b94f2)
       (blue-1bg    . #x023447)
       (blue-1fg    . #x649bce)
       (blue-2bg    . #x004363)
       (blue-2fg    . #x78a3cb)
       (blue-d      . #x0069b0)
       (blue-l      . #x7ebaff)
       (cyan-1bg    . #x03373f)
       (cyan-1fg    . #x60aca4)
       (cyan-2bg    . #x004b4f)
       (cyan-2fg    . #x73b0aa)
       (cyan-d      . #x008981)
       (cyan-l      . #x77dece)
       (green-1bg   . #x1e3531)
       (green-1fg   . #x97a54d)
       (green-2bg   . #x354725)
       (green-2fg   . #x9eaa66)
       (green-d     . #x687f00)
       (green-l     . #xc3d255)
       ;; palette end
       )))
  "The solarized color palette alist.")

(defconst solarized-light-high-contrast-palette
  (eval-when-compile
    (make-solarized-palette
     t
     '(;; solarized-light-high-contrast palette
       (base03      . #x00212b)
       (base02      . #x002b37)
       (base01      . #x5d737a)
       (base00      . #x596e76)
       (base0       . #x88999b)
       (base1       . #x98a6a6)
       (base2       . #xf4eedb)
       (base3       . #xfffce9)
       (yellow      . #xa67c00)
       (orange      . #xbb3e06)
       (red         . #xcc1f24)
       (magenta     . #xc42475)
       (violet      . #x5e65b6)
       (blue        . #x007ec4)
       (cyan        . #x11948b)
       (green       . #x778c00)
       (yellow-1bg  . #xf7eacb)
       (yellow-1fg  . #x7a6120)
       (yellow-2bg  . #xecd29c)
       (yellow-2fg  . #x6b5a2c)
       (yellow-d    . #x785700)
       (yellow-l    . #xd6a549)
       (orange-1bg  . #xfee2c8)
       (orange-1fg  . #x8a3b1c)
       (orange-2bg  . #xfabc97)
       (orange-2fg  . #x793e28)
       (orange-d    . #x891b00)
       (orange-l    . #xed6e3e)
       (red-1bg     . #xffe1cb)
       (red-1fg     . #x952f2a)
       (red-2bg     . #xffb79f)
       (red-2fg     . #x823731)
       (red-d       . #x990001)
       (red-l       . #xff6243)
       (magenta-1bg . #xfce1da)
       (magenta-1fg . #x8e3160)
       (magenta-2bg . #xf9b9c4)
       (magenta-2fg . #x7a395c)
       (magenta-d   . #x93004d)
       (magenta-l   . #xf46495)
       (violet-1bg  . #xebe7e5)
       (violet-1fg  . #x44528c)
       (violet-2bg  . #xcdc8e1)
       (violet-2fg  . #x3d4f7e)
       (violet-d    . #x11328f)
       (violet-l    . #x837bdf)
       (blue-1bg    . #xe6ebe7)
       (blue-1fg    . #x0a6395)
       (blue-2bg    . #xbfd2e6)
       (blue-2fg    . #x185b85)
       (blue-d      . #x005797)
       (blue-l      . #x6fa5e7)
       (cyan-1bg    . #xe4efdd)
       (cyan-1fg    . #x10716f)
       (cyan-2bg    . #xb9ddcd)
       (cyan-2fg    . #x196767)
       (cyan-d      . #x006d68)
       (cyan-l      . #x66c1b3)
       (green-1bg   . #xeeedcb)
       (green-1fg   . #x596c21)
       (green-2bg   . #xd5d99d)
       (green-2fg   . #x51622d)
       (green-d     . #x4f6600)
       (green-l     . #xa8b84b)
       ;; palette end
       )))
  "The solarized color palette alist.")

;;; gruvbox themes

;; (defconst solarized-gruvbox-colors
;;   '(;; gruvbox colors
;;     (dark0_hard    . #x1d2021)
;;     (dark0         . #x282828)
;;     (dark0_soft    . #x32302f)
;;     (dark1         . #x3c3836)
;;     (dark2         . #x504945)
;;     (dark3         . #x665c54)
;;     (dark4         . #x7c6f64)
;;     (gray          . #x928374)
;;     (light0_hard   . #xf9f5d7)
;;     (light0        . #xfbf1c7)
;;     (light0_soft   . #xf2e5bc)
;;     (light1        . #xebdbb2)
;;     (light2        . #xd5c4a1)
;;     (light3        . #xbdae93)
;;     (light4        . #xa89984)
;;     (red           . #xcc241d)
;;     (green         . #x98971a)
;;     (yellow        . #xd79921)
;;     (blue          . #x458588)
;;     (purple        . #xb16286)
;;     (aqua          . #x689d6a)
;;     (orange        . #xd65d0e)
;;     (bright_red    . #xfb4933)
;;     (bright_green  . #xb8bb26)
;;     (bright_yellow . #xfabd2f)
;;     (bright_blue   . #x83a598)
;;     (bright_purple . #xd3869b)
;;     (bright_aqua   . #x8ec07c)
;;     (bright_orange . #xfe8019)
;;     (dark_red      . #x9d0006)
;;     (dark_green    . #x79740e)
;;     (dark_yellow   . #xb57614)
;;     (dark_blue     . #x076678)
;;     (dark_purple   . #x8f3f71)
;;     (dark_aqua     . #x427b58)
;;     (dark_orange   . #xaf3a03)
;;     ;; colors end
;;     )
;;   "The gruvbox color palette.")

(defconst solarized-gruvbox-dark-color-palette
  (eval-when-compile
    (make-solarized-palette
     nil
     '(;; gruvbox-dark palette
       (base03      . #x282828)
       (base02      . #x32302f)
       (base01      . #x7c6f64)
       (base00      . #x282828)
       (base0       . #xa89984)
       (base1       . #xbdae93)
       (base2       . #xa89984)
       (base3       . #xfbf1c7)
       (yellow      . #xd79921)
       (orange      . #xd65d0e)
       (red         . #xfb4933)
       (magenta     . #xd3869b)
       (violet      . #xb16286)
       (blue        . #x458588)
       (cyan        . #x689d6a)
       (green       . #x98971a)
       (yellow-1bg  . #x3f3528)
       (yellow-1fg  . #xe2b055)
       (yellow-2bg  . #x614923)
       (yellow-2fg  . #xdfb566)
       (yellow-d    . #xa76e00)
       (yellow-l    . #xf3ac41)
       (orange-1bg  . #x402e25)
       (orange-1fg  . #xe48847)
       (orange-2bg  . #x62351c)
       (orange-2fg  . #xe2965a)
       (orange-d    . #xa53600)
       (orange-l    . #xf37535)
       (red-1bg     . #x452e28)
       (red-1fg     . #xff815b)
       (red-2bg     . #x6f3125)
       (red-2fg     . #xf89169)
       (red-d       . #xb21b0b)
       (red-l       . #xff6540)
       (magenta-1bg . #x3d3335)
       (magenta-1fg . #xdda3a6)
       (magenta-2bg . #x5e434a)
       (magenta-2fg . #xdbaba4)
       (magenta-d   . #x9f4d64)
       (magenta-l   . #xe78c9e)
       (violet-1bg  . #x392f33)
       (violet-1fg  . #xc68a97)
       (violet-2bg  . #x523642)
       (violet-2fg  . #xc89798)
       (violet-d    . #x8b2a58)
       (violet-l    . #xd36b91)
       (blue-1bg    . #x2c3333)
       (blue-1fg    . #x7da298)
       (blue-2bg    . #x2d4243)
       (blue-2fg    . #x90aa99)
       (blue-d      . #x14676b)
       (blue-l      . #x63a6a5)
       (cyan-1bg    . #x2f362f)
       (cyan-1fg    . #x91b382)
       (cyan-2bg    . #x384a38)
       (cyan-2fg    . #x9fb888)
       (cyan-d      . #x2e7d33)
       (cyan-l      . #x75bf6b)
       (green-1bg   . #x363527)
       (green-1fg   . #xb4ae51)
       (green-2bg   . #x4a4821)
       (green-2fg   . #xbab462)
       (green-d     . #x747400)
       (green-l     . #xb9b340)
       ;; palette end
       )))
  "The solarized gruvbox dark palette color alist.")

(defconst solarized-gruvbox-light-color-palette
  (eval-when-compile
    (make-solarized-palette
     t
     '(;; gruvbox-light palette
       (base03      . #x282828)
       (base02      . #x32302f)
       (base01      . #x665c54)
       (base00      . #x7c6f64)
       (base0       . #x3c3836)
       (base1       . #xa89984)
       (base2       . #xebdbb2)
       (base3       . #xfbf1c7)
       (yellow      . #xb57614)
       (orange      . #xaf3a03)
       (red         . #x9d0006)
       (magenta     . #xd3869b)
       (violet      . #x8f3f71)
       (blue        . #x076678)
       (cyan        . #x689d6a)
       (green       . #x98971a)
       (yellow-1bg  . #xf6e1af)
       (yellow-1fg  . #x8c6023)
       (yellow-2bg  . #xefc98b)
       (yellow-2fg  . #x7f5b2d)
       (yellow-d    . #x8a5100)
       (yellow-l    . #xe29a3f)
       (orange-1bg  . #xf7d8ab)
       (orange-1fg  . #x893a18)
       (orange-2bg  . #xf0b382)
       (orange-2fg  . #x7e3e23)
       (orange-d    . #x841900)
       (orange-l    . #xdf6835)
       (red-1bg     . #xf5d4aa)
       (red-1fg     . #x7e2115)
       (red-2bg     . #xeaa67f)
       (red-2fg     . #x752d21)
       (red-d       . #x750000)
       (red-l       . #xcf5130)
       (magenta-1bg . #xf9e4c3)
       (magenta-1fg . #x9e6b78)
       (magenta-2bg . #xf8d1c0)
       (magenta-2fg . #x8c646e)
       (magenta-d   . #x9f4d64)
       (magenta-l   . #xf598a7)
       (violet-1bg  . #xeed8bd)
       (violet-1fg  . #x713c5c)
       (violet-2bg  . #xdcb3af)
       (violet-2fg  . #x694058)
       (violet-d    . #x6f104d)
       (violet-l    . #xc2608f)
       (blue-1bg    . #xdedebe)
       (blue-1fg    . #x245561)
       (blue-2bg    . #xb1c2b2)
       (blue-2fg    . #x30535c)
       (blue-d      . #x004858)
       (blue-l      . #x5b919b)
       (cyan-1bg    . #xe7e7bb)
       (cyan-1fg    . #x577a58)
       (cyan-2bg    . #xcbdaab)
       (cyan-2fg    . #x556f55)
       (cyan-d      . #x2e7d33)
       (cyan-l      . #x82cc73)
       (green-1bg   . #xf0e6b1)
       (green-1fg   . #x787628)
       (green-2bg   . #xe0d78f)
       (green-2fg   . #x6f6c32)
       (green-d     . #x747400)
       (green-l     . #xc6c148)
       ;; palette end
       )))
  "The solarized gruvbox light color palette alist.")

(defconst solarized-zenburn-color-palette
  (eval-when-compile
    (make-solarized-palette
     nil ;; Not sure about this one
     '(;; zenburn palette
       (base03      . #x3F3F3F)
       (base02      . #x4F4F4F)
       (base01      . #x878777)
       (base00      . #x6F6F6F)
       (base0       . #xDCDCCC)
       (base1       . #xFFFFEF)
       (base2       . #xfffff6)
       (base3       . #xFFFFFD)
       (yellow      . #xF0DFAF)
       (orange      . #xDFAF8F)
       (red         . #xCC9393)
       (magenta     . #xDC8CC3)
       (violet      . #xbbb0cb)
       (blue        . #x8CD0D3)
       (cyan        . #x93E0E3)
       (green       . #x7F9F7F)
       (yellow-1bg  . #x55524c)
       (yellow-1fg  . #xf2e6c3)
       (yellow-2bg  . #x777160)
       (yellow-2fg  . #xece2c7)
       (yellow-d    . #xb6a576)
       (yellow-l    . #xfff7c4)
       (orange-1bg  . #x534c48)
       (orange-1fg  . #xe7c4ac)
       (orange-2bg  . #x726054)
       (orange-2fg  . #xe4c7b4)
       (orange-d    . #xac7b5a)
       (orange-l    . #xffcaa5)
       (red-1bg     . #x504948)
       (red-1fg     . #xdab0af)
       (red-2bg     . #x6b5656)
       (red-2fg     . #xd9b8b6)
       (red-d       . #x9f5c5c)
       (red-l       . #xf4a9a6)
       (magenta-1bg . #x52484f)
       (magenta-1fg . #xe5acd1)
       (magenta-2bg . #x705467)
       (magenta-2fg . #xe2b5d2)
       (magenta-d   . #xaa5790)
       (magenta-l   . #xffa6e0)
       (violet-1bg  . #x4e4c50)
       (violet-1fg  . #xccc4d7)
       (violet-2bg  . #x64606a)
       (violet-2fg  . #xcec8d6)
       (violet-d    . #x85749c)
       (violet-l    . #xd5c3ec)
       (blue-1bg    . #x495051)
       (blue-1fg    . #xaddbdd)
       (blue-2bg    . #x556c6c)
       (blue-2fg    . #xb7dada)
       (blue-d      . #x57a2a4)
       (blue-l      . #xa9f4f5)
       (cyan-1bg    . #x4a5253)
       (cyan-1fg    . #xb3e7e8)
       (cyan-2bg    . #x577172)
       (cyan-2fg    . #xbbe3e3)
       (cyan-d      . #x5dacaf)
       (cyan-l      . #xb0ffff)
       (green-1bg   . #x464a46)
       (green-1fg   . #xa2b8a1)
       (green-2bg   . #x4f5a4e)
       (green-2fg   . #xacbeab)
       (green-d     . #x488249)
       (green-l     . #x95d291)
       ;; palette end
       )))
  "The solarized color palette alist.")

(defconst solarized-selenized-dark-color-palette
  (eval-when-compile
    (make-solarized-palette
     nil
     '(;; selenized-dark palette
       (base03      . #x103c48)
       (base02      . #x184956)
       (base01      . #x72898f)
       (base00      . #x103c48)
       (base0       . #xadbcbc)
       (base1       . #xcad8d9)
       (base2       . #xece3cc)
       (base3       . #xfbf3db)
       (yellow      . #xdbb32d)
       (orange      . #xed8649)
       (red         . #xfa5750)
       (magenta     . #xf275be)
       (violet      . #xaf88eb)
       (blue        . #x4695f7)
       (cyan        . #x41c7b9)
       (green       . #x75b938)
       (yellow-1bg  . #x374a45)
       (yellow-1fg  . #xe5c364)
       (yellow-2bg  . #x615f3c)
       (yellow-2fg  . #xe2c475)
       (yellow-d    . #xac8a0c)
       (yellow-l    . #xffd557)
       (orange-1bg  . #x3b4547)
       (orange-1fg  . #xf3a471)
       (orange-2bg  . #x685042)
       (orange-2fg  . #xedac7f)
       (orange-d    . #xb45b24)
       (orange-l    . #xffa361)
       (red-1bg     . #x3f4147)
       (red-1fg     . #xfe8875)
       (red-2bg     . #x6f4443)
       (red-2fg     . #xf79781)
       (red-d       . #xb42e2a)
       (red-l       . #xff7c65)
       (magenta-1bg . #x374456)
       (magenta-1fg . #xf49bc4)
       (magenta-2bg . #x664d6b)
       (magenta-2fg . #xeda5c0)
       (magenta-d   . #xb3478d)
       (magenta-l   . #xff92d2)
       (violet-1bg  . #x29455c)
       (violet-1fg  . #xc6a5e4)
       (violet-2bg  . #x48517b)
       (violet-2fg  . #xc9adda)
       (violet-d    . #x7255b7)
       (violet-l    . #xca9cff)
       (blue-1bg    . #x16465d)
       (blue-1fg    . #x8daded)
       (blue-2bg    . #x18557f)
       (blue-2fg    . #x9fb3e0)
       (blue-d      . #x0068bb)
       (blue-l      . #x82afff)
       (cyan-1bg    . #x144d55)
       (cyan-1fg    . #x85d2c0)
       (cyan-2bg    . #x156669)
       (cyan-2fg    . #x98d0bd)
       (cyan-d      . #x00a195)
       (cyan-l      . #x7cefda)
       (green-1bg   . #x244b46)
       (green-1fg   . #x9dc869)
       (green-2bg   . #x37613e)
       (green-2fg   . #xa9c879)
       (green-d     . #x489615)
       (green-l     . #x9fe35b)
       ;; palette end
       )))
  "The solarized color palette alist")

(defconst solarized-selenized-black-color-palette
  (eval-when-compile
    (make-solarized-palette
     nil
     '(;; selenized-black color palette
       (base03      . #x181818)
       (base02      . #x252525)
       (base01      . #x777777)
       (base00      . #x181818)
       (base0       . #xb9b9b9)
       (base1       . #xdedede)
       (base2       . #x53676d)
       (base3       . #x3a4d53)
       (yellow      . #xdbb32d)
       (orange      . #xe67f43)
       (red         . #xed4a46)
       (magenta     . #xeb6eb7)
       (violet      . #xa580e2)
       (blue        . #x368aeb)
       (cyan        . #x3fc5b7)
       (green       . #x70b433)
       (yellow-1bg  . #x302a1c)
       (yellow-1fg  . #xdebd66)
       (yellow-2bg  . #x56471d)
       (yellow-2fg  . #xd7bb78)
       (yellow-d    . #xa68000)
       (yellow-l    . #xe5bb45)
       (orange-1bg  . #x32241d)
       (orange-1fg  . #xe7996e)
       (orange-2bg  . #x5a3621)
       (orange-2fg  . #xde9f7d)
       (orange-d    . #xaa4b11)
       (orange-l    . #xeb844a)
       (red-1bg     . #x331f1d)
       (red-1fg     . #xee7a6e)
       (red-2bg     . #x5d2621)
       (red-2fg     . #xe5887d)
       (red-d       . #xad1117)
       (red-l       . #xf15a4b)
       (magenta-1bg . #x31232a)
       (magenta-1fg . #xe790c0)
       (magenta-2bg . #x5b3148)
       (magenta-2fg . #xdd99bd)
       (magenta-d   . #xac357c)
       (magenta-l   . #xe973b8)
       (violet-1bg  . #x29242f)
       (violet-1fg  . #xb599df)
       (violet-2bg  . #x433657)
       (violet-2fg  . #xb69fd6)
       (violet-d    . #x6945a5)
       (violet-l    . #xa07de4)
       (blue-1bg    . #x202530)
       (blue-1fg    . #x7a9fe5)
       (blue-2bg    . #x25395a)
       (blue-2fg    . #x8aa4db)
       (blue-d      . #x0057af)
       (blue-l      . #x518eee)
       (cyan-1bg    . #x202c2a)
       (cyan-1fg    . #x7acac0)
       (cyan-2bg    . #x254d48)
       (cyan-2fg    . #x89c6bd)
       (cyan-d      . #x009789)
       (cyan-l      . #x50d3c5)
       (green-1bg   . #x232a1c)
       (green-1fg   . #x92be67)
       (green-2bg   . #x32471d)
       (green-2fg   . #x9bbc78)
       (green-d     . #x428800)
       (green-l     . #x7bc447)
       ;; palette end
       )))
  "The solarized color palette alist")

(defconst solarized-selenized-light-color-palette
  (eval-when-compile
    (make-solarized-palette
     t
     '( ;; selenized-light palette
       (base03      . #xfbf3db)
       (base02      . #xece3cc)
       (base01      . #x909995)
       (base00      . #xfbf3db)
       (base0       . #x53676d)
       (base1       . #x3a4d53)
       (base2       . #xadbcbc)
       (base3       . #xcad8d9)
       (yellow      . #xad8900)
       (orange      . #xc25d1e)
       (red         . #xd2212d)
       (magenta     . #xca4898)
       (violet      . #x8762c6)
       (blue        . #x0072d4)
       (cyan        . #x009c8f)
       (green       . #x489100)
       (yellow-1bg  . #xf4e5c0)
       (yellow-1fg  . #x90792f)
       (yellow-2bg  . #xedd397)
       (yellow-2fg  . #x887640)
       (yellow-d    . #xb08b24)
       (yellow-l    . #xcea847)
       (orange-1bg  . #xf9dfc0)
       (orange-1fg  . #xa05c34)
       (orange-2bg  . #xf7c198)
       (orange-2fg  . #x956143)
       (orange-d    . #xc65e21)
       (orange-l    . #xe67b41)
       (red-1bg     . #xfedac1)
       (red-1fg     . #xac403b)
       (red-2bg     . #xffb39b)
       (red-2fg     . #xa04e48)
       (red-d       . #xd53926)
       (red-l       . #xf65a45)
       (magenta-1bg . #xf9ddd4)
       (magenta-1fg . #xa35285)
       (magenta-2bg . #xf7bdcb)
       (magenta-2fg . #x955b82)
       (magenta-d   . #xcd488f)
       (magenta-l   . #xea68b0)
       (violet-1bg  . #xeedfdb)
       (violet-1fg  . #x735fa5)
       (violet-2bg  . #xdbc2df)
       (violet-2fg  . #x6f649b)
       (violet-d    . #x8355c0)
       (violet-l    . #x9c72e4)
       (blue-1bg    . #xe4e1de)
       (blue-1fg    . #x3369ae)
       (blue-2bg    . #xc0c7e5)
       (blue-2fg    . #x426ba2)
       (blue-d      . #x4872cb)
       (blue-l      . #x608eef)
       (cyan-1bg    . #xe1e9d2)
       (cyan-1fg    . #x2d867f)
       (cyan-2bg    . #xb9dcc8)
       (cyan-2fg    . #x3b817d)
       (cyan-d      . #x3ea08e)
       (cyan-l      . #x55beaf)
       (green-1bg   . #xe4e7bf)
       (green-1fg   . #x4b7f2e)
       (green-2bg   . #xc1d795)
       (green-2fg   . #x527c3f)
       (green-d     . #x569623)
       (green-l     . #x70b447)
       ;; palette end
       )))
  "The solarized color palette alist")

(defconst solarized-selenized-white-color-palette
  (eval-when-compile
    (make-solarized-palette
     t
     '(;; selenized-white palette
       (base03      . #xffffff)
       (base02      . #xebebeb)
       (base01      . #x878787)
       (base00      . #xffffff)
       (base0       . #x474747)
       (base1       . #x282828)
       (base2       . #xb9b9b9)
       (base3       . #xdedede)
       (yellow      . #xc49700)
       (orange      . #xd04a00)
       (red         . #xd6000c)
       (magenta     . #xdd0f9d)
       (violet      . #x7f51d6)
       (blue        . #x0064e4)
       (cyan        . #x00ad9c)
       (green       . #x1d9700)
       (yellow-1bg  . #xfdf1df)
       (yellow-1fg  . #x967621)
       (yellow-2bg  . #xfadfae)
       (yellow-2fg  . #x866c2d)
       (yellow-d    . #xc7992f)
       (yellow-l    . #xe5b34a)
       (orange-1bg  . #xffe7db)
       (orange-1fg  . #xa04519)
       (orange-2bg  . #xffc2a5)
       (orange-2fg  . #x8f4726)
       (orange-d    . #xd35323)
       (orange-l    . #xf36e3c)
       (red-1bg     . #xffe3db)
       (red-1fg     . #xa4291b)
       (red-2bg     . #xffb7a4)
       (red-2fg     . #x933526)
       (red-d       . #xd93920)
       (red-l       . #xf95738)
       (magenta-1bg . #xffe5f3)
       (magenta-1fg . #xa72f7a)
       (magenta-2bg . #xffbce2)
       (magenta-2fg . #x933a6f)
       (magenta-d   . #xde3e9c)
       (magenta-l   . #xfc5db8)
       (violet-1bg  . #xf1e7fc)
       (violet-1fg  . #x6848a0)
       (violet-2bg  . #xdbc3fb)
       (violet-2fg  . #x63498d)
       (violet-d    . #x7d4bd4)
       (violet-l    . #x9a64f2)
       (blue-1bg    . #xe8e9ff)
       (blue-1fg    . #x3453aa)
       (blue-2bg    . #xc4c8ff)
       (blue-2fg    . #x405194)
       (blue-d      . #x4965e0)
       (blue-l      . #x6a7efd)
       (cyan-1bg    . #xe5f6f2)
       (cyan-1fg    . #x2e8579)
       (cyan-2bg    . #xbceae2)
       (cyan-2fg    . #x3a786f)
       (cyan-d      . #x3fb09f)
       (cyan-l      . #x5eccbb)
       (green-1bg   . #xe4f3de)
       (green-1fg   . #x31761f)
       (green-2bg   . #xbbe1ab)
       (green-2fg   . #x3a6d2b)
       (green-d     . #x3e9e2d)
       (green-l     . #x5cb947)
       ;; palette end
       )))
  "The solarized color palette alist")

(provide 'solarized-palettes)

;; Local Variables:
;; indent-tabs-mode: nil
;; End:

;;; solarized-palettes.el ends here
