# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 1

init:

install:
  - ps: Invoke-WebRequest "https://ftp.gnu.org/gnu/emacs/windows/emacs-24.5-bin-i686-mingw32.zip" -OutFile "emacs-24.5-bin-i686-mingw32.zip"
  - 7z x emacs-24.5-bin-i686-mingw32.zip


build_script:
  - C:\msys64\usr\bin\bash -l -c "cd ${APPVEYOR_BUILD_FOLDER} && make check compile EMACS=./bin/emacs.exe"

test_script:
